enh(centreon): update the plugin packs term to monitoring connectors
centreon/centreon pull request #1069
Opened 2023-03-08 16:53 UTC by adr-mo

## Description

CURRENTLY IN DRAFT AS I AM TESTING IT USING PACKAGES FOR INSTALL / UPDATE / RENDERING with TRADS

🏷️ MON-16550

This PR intends to change the naming from "plugin packs" / "plugin pack manager" (only for the UI) to "Monitoring connectors" / "Monitoring Connectors Manager"

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [X] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Jira

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-03-10 08:20 UTC, abuathier approved these changes

2023-03-10 09:56 UTC, smau-centreon requested changes

2023-03-10 09:56 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Conectores de Supervisión"
```suggestion
msgstr "Conectores de supervisión"
```

2023-03-10 09:56 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Connecteurs de Supervision"
```suggestion
msgstr "Connecteurs de supervision"
```

2023-03-10 09:56 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Conectores de Supervisão"
```suggestion
msgstr "Conectores de supervisão"
```

2023-03-10 09:56 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Conectores de Supervisão"
```suggestion
msgstr "Conectores de supervisão"
```

2023-03-10 11:03 UTC, wtermellil submitted a review, later dismissed

2023-03-10 12:57 UTC, smau-centreon approved these changes

2023-03-10 13:25 UTC, callapa approved these changes

2023-03-13 09:08 UTC, abuathier approved these changes

2023-03-14 13:47 UTC, merged