feat(UI): Improve about page
centreon/centreon pull request #1090
Opened 2023-03-10 17:02 UTC by Thebarda

## Description

This migrates the About page to React.

https://user-images.githubusercontent.com/12515407/224377451-259d944b-1b3a-4cae-b448-bc2048eaa1d1.mov

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

- The about page should be displayed

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-03-13 08:54 UTC, Wedierre submitted a review, later dismissed

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          description: "Custom text display on login page on JSON format"
```suggestion
          description: "Custom text display on login page in JSON format"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +            "text": "Welcome on Centreon", "type": "text", "version": 1}]'
```suggestion
            "text": "Welcome to Centreon", "type": "text", "version": 1}]'
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +                  description: "Id of the icon"
```suggestion
                  description: "ID of the icon"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +              description: "Select custom icon"
```suggestion
              description: "Select a custom icon"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +                  description: "Id of the image"
```suggestion
                  description: "ID of the image"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +              description: "Select custom icon id"
```suggestion
              description: "Select custom icon ID"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +              description: "Select custom image id"
```suggestion
              description: "Select custom image ID"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          description: "Custom text display on login page on JSON format"
```suggestion
          description: "Custom text display on login page in JSON format"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +            "text": "Welcome on Centreon", "type": "text", "version": 1}]'
```suggestion
            "text": "Welcome to Centreon", "type": "text", "version": 1}]'
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          description: "Id of the image to resize"
```suggestion
          description: "ID of the image to resize"
```

2023-03-13 10:54 UTC, cg-tw commented on centreon/www/front_src/src/About/Sections/Developers.tsx
> +  "Bruno D'auria",
```suggestion
  "Bruno D'Auria",

```

2023-03-13 10:54 UTC, cg-tw commented on centreon/www/front_src/src/About/translatedLabels.ts
> +export const labelYouCanSeeFullListOnThe = 'You can see the full list on the';
si le but c'est de concaténer avec "Centreon's GitHub", il faut pas mettre le "the"

2023-03-13 12:35 UTC, cg-tw commented on centreon/www/front_src/src/About/Sections/Developers.tsx
> +
```suggestion
```

2023-03-13 12:39 UTC, cg-tw submitted a review, later dismissed

2023-03-20 09:14 UTC, jeremyjaouen requested changes

2023-03-20 09:14 UTC, jeremyjaouen commented on centreon/doc/API/centreon-api-v23.04.yaml
> +    + Added image resizing endpoints (POST)
```suggestion
```

2023-03-20 09:14 UTC, jeremyjaouen commented on centreon/doc/API/centreon-api-v23.04.yaml
> +    + Added image resizing endpoints (POST)
this has been moved into the module

2023-03-20 09:14 UTC, jeremyjaouen commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          $ref: '#/components/responses/InternalServerError'
```suggestion
```
this has been moved into the module

2023-03-20 09:14 UTC, jeremyjaouen commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          example: 20
```suggestion
```
this has been moved into the module

2023-03-20 09:42 UTC, cg-tw approved these changes

2023-03-20 09:54 UTC, Wedierre approved these changes

2023-03-21 07:55 UTC, cg-tw commented on centreon/doc/API/centreon-api-v23.04.yaml
> +          description: "Vault role id"
```suggestion
          description: "Vault role ID"
```

2023-03-21 08:16 UTC, cg-tw submitted a review, later dismissed

2023-03-21 08:31 UTC, bdauria approved these changes

2023-03-21 08:51 UTC, SoldierBoy31 approved these changes

2023-03-21 10:13 UTC, Wedierre approved these changes

2023-03-21 11:13 UTC, cg-tw approved these changes

2023-03-22 10:20 UTC, jeremyjaouen approved these changes

2023-03-22 14:24 UTC, kduret approved these changes

2023-03-22 14:26 UTC, merged