fix (Authentication): Make error messages generic
centreon/centreon pull request #1195
Opened 2023-03-29 00:09 UTC by emabassi-ext

## Description
When user reach maximum number of authentication attempts, Centreon logs must indicate that.

**Fixes** #MON-16740

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

See example mapping in jira ticket

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-03-29 06:46 UTC, kduret commented on centreon/src/Security/Domain/Authentication/Model/LocalProvider.php
> +                "[local] User is blocked: maximum number of authentication attempts was reached"
IMHO user alias should be in the log message

2023-03-29 07:13 UTC, callapa requested changes

2023-03-29 07:13 UTC, callapa commented on centreon/src/Security/Domain/Authentication/Model/LocalProvider.php
> +        $this->centreonLog = new CentreonUserLog(-1, $pearDB);
The old service container should no longer be used in class constructors

2023-04-11 10:31 UTC, jeremyjaouen commented
Fix already handled by this PR https://github.com/centreon/centreon/pull/1201/files

2023-04-11 10:31 UTC, closed without merging