enh(openid): Add custom redirect_url - 22.10 (#1276)
centreon/centreon pull request #1279
Opened 2023-04-06 13:12 UTC by dmyios

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Backport of https://github.com/centreon/centreon/pull/1200 to 22.10

**Fixes** # MON-18051

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x
- [ ] 23.04.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-04-06 15:47 UTC, Thebarda approved these changes

2023-04-06 16:07 UTC, dmyios commented on centreon/www/install/php/Update-22.10.8.php
> +                SET custom_configuration = $updatedCustomConfigurationEncoded
```suggestion
                SET custom_configuration = '$updatedCustomConfigurationEncoded'
```

2023-04-06 16:07 UTC, dmyios commented on centreon/www/install/php/Update-22.10.8.php
> +    $errorMessage = 'Unable to update OpenId custom configuration';
```suggestion
    $errorMessage = 'Unable to update provider_configuration table to add redirect_url';
```

2023-04-06 16:56 UTC, jeremyjaouen requested changes

2023-04-06 16:56 UTC, jeremyjaouen commented on centreon/www/install/php/Update-22.10.8.php
> +    }
please use a prepare statement

2023-04-07 07:22 UTC, dmyios commented on centreon/www/install/php/Update-22.10.8.php
> +        $statement->bindValue('encodedConfiguration', $updatedCustomConfigurationEncoded, \PDO::PARAM_STR);
```suggestion
        $statement->bindValue(':encodedConfiguration', $updatedCustomConfigurationEncoded, \PDO::PARAM_STR);
```

2023-04-07 07:22 UTC, dmyios commented on centreon/www/install/php/Update-22.10.8.php
> +    }
Done

2023-04-11 07:41 UTC, jeremyjaouen approved these changes

2023-04-11 08:21 UTC, merged