fix(resource): return host when searching with h.name
centreon/centreon pull request #1340
Opened 2023-04-17 20:08 UTC by adr-mo

ℹ️ MON-18040

This PR intends to return also the host when searching h.name:[search]
I've used CONCAT in the concordanceArray for the h.name which corresponds to `resources.name REGEXP [search] OR resources.parent_name REGEXP [search]`

Here is the difference between both types of requests. CONCAT here is only used with 2 columns which should not impact much performances (h.name filter is not used that much and should disappear with 23.10)

![image](https://user-images.githubusercontent.com/31647811/232598063-5a9c4363-1959-451d-b6a7-32567b19ec65.png)

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

See MON-18040

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-04-18 13:00 UTC, dmyios approved these changes

2023-04-18 13:50 UTC, abuathier approved these changes

2023-04-18 13:51 UTC, abuathier requested changes
After first read, something is triggering me : this does not work anymore with equal comparison in sql translator

2023-04-18 14:00 UTC, abuathier submitted a review, later dismissed

2023-05-05 12:00 UTC, dmyios approved these changes

2023-05-05 14:07 UTC, abuathier submitted a review, later dismissed

2023-05-05 15:18 UTC, callapa requested changes

2023-05-05 15:18 UTC, callapa commented on centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
> +        'h.name' => 'CONCAT(resources.parent_name, resources.name)',
Indeed, your proposal breaks the EQUAL operator.
```suggestion
        'h.name' => 'CASE type WHEN 1 THEN `resources.name` ELSE `resources.parent_name` END',
```

2023-05-10 08:32 UTC, callapa approved these changes

2023-05-10 08:33 UTC, adr-mo commented on centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
> +        // We know this trick breaks the EQUAL, but this is theoretically ONLY used as REGEX from the Resource status
```suggestion
```

2023-05-10 08:34 UTC, callapa approved these changes

2023-05-10 08:41 UTC, jeremyjaouen submitted a review, later dismissed

2023-05-10 08:59 UTC, dmyios submitted a review, later dismissed

2023-05-11 09:05 UTC, abuathier approved these changes

2023-05-12 08:25 UTC, dmyios approved these changes

2023-05-12 08:32 UTC, wtermellil approved these changes

2023-05-12 08:37 UTC, adr-mo commented on centreon/src/Core/Resources/Infrastructure/Repository/DbReadResourceRepository.php
> +        // We know this trick breaks the EQUAL, but this is theoretically ONLY used as REGEX from the Resource status
```suggestion
```

2023-05-12 08:37 UTC, wtermellil submitted a review, later dismissed

2023-05-12 08:38 UTC, abuathier approved these changes

2023-05-12 09:10 UTC, wtermellil approved these changes

2023-05-12 09:21 UTC, merged