feat(UI): Cancel Dashboard changes
centreon/centreon pull request #1521
Opened 2023-05-29 09:29 UTC by Thebarda

## Description

This adds the cancel dashboard feature. It also handles the route navigation in order to display a message while the user is editing the dashboard.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

- Create a dashboard
- Click on the created dashboard
- Click the "Edit" button
- Edit the dashboard
- Click on "Cancel"
- Click on the cancel button in the confirmation dialog
- -> The dashboard changes are canceled

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-05-31 13:10 UTC, smau-centreon requested changes

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "If you leave {{dashboardName}}, you changes will not be saved."
```suggestion
# msgid "If you leave {{dashboardName}}, your changes will not be saved."
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "If you leave {{dashboardName}}, you changes will not be saved."
```suggestion
# msgid "If you leave {{dashboardName}}, your changes will not be saved."
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Editer le tableau de bord"
```suggestion
msgstr "Éditer le tableau de bord"
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "If you leave {{dashboardName}}, you changes will not be saved."
```suggestion
msgid "If you leave {{dashboardName}}, your changes will not be saved."
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "If you leave {{dashboardName}}, you changes will not be saved."
```suggestion
# msgid "If you leave {{dashboardName}}, your changes will not be saved."
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "If you leave {{dashboardName}}, you changes will not be saved."
```suggestion
# msgid "If you leave {{dashboardName}}, your changes will not be saved."
```

2023-05-31 13:10 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
> +  'If you leave {{dashboardName}}, you changes will not be saved.';
```suggestion
  'If you leave {{dashboardName}}, your changes will not be saved.';

```

2023-05-31 15:26 UTC, smau-centreon submitted a review, later dismissed

2023-06-02 11:05 UTC, g10 requested changes

2023-06-05 08:25 UTC, g10 approved these changes

2023-06-05 08:48 UTC, smau-centreon approved these changes

2023-06-05 08:49 UTC, merged