fix(e2e): Add more timeout to acknowledgments
centreon/centreon pull request #1529
Opened 2023-05-29 13:10 UTC by hyahiaoui-ext

## Description

Add more timeout to acknowledgments E2E tests to avoid random fails and give it more room to wait for ressources.

**Fixes** # MON-19533

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-05-29 13:28 UTC, kduret approved these changes

2023-05-29 13:49 UTC, kduret requested changes
check resources are monitored before trying to submit external commands

2023-05-29 13:59 UTC, hyahiaoui-ext commented
> check resources are monitored before trying to submit external commands

i replace it with "startwebcontainer" it should do the trick

2023-05-29 14:17 UTC, bdauria submitted a review, later dismissed

2023-05-29 14:31 UTC, kduret reviewed
it seems there are some other random fails on downtime tests

2023-05-29 14:33 UTC, hyahiaoui-ext commented
> it seems there are some other random fails on downtime tests

Yes i messup something ^^' will retry now !

2023-05-30 06:43 UTC, kduret commented on centreon/tests/e2e/cypress/e2e/Resources-status/02-acknowledgments/index.ts
> +  cy.startWebContainer();
why not starting container in `beforeEach` and stopping it in `afterEach` ?

2023-05-30 08:30 UTC, kduret approved these changes

2023-05-30 08:30 UTC, kduret approved these changes

2023-05-30 08:33 UTC, bdauria approved these changes

2023-05-30 08:34 UTC, merged