feat(dashboard): Save a dashboard
centreon/centreon pull request #1600
Opened 2023-06-07 15:58 UTC by abuathier

## Description

Jira [feature] **MON-18497**

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-06-08 13:41 UTC, Thebarda approved these changes

2023-06-08 13:46 UTC, dmyios approved these changes

2023-06-08 14:18 UTC, bdauria submitted a review, later dismissed

2023-06-08 14:23 UTC, jeremyjaouen submitted a review, later dismissed

2023-06-08 17:20 UTC, g10 approved these changes

2023-06-08 17:37 UTC, jeremyjaouen submitted a review, later dismissed

2023-06-09 06:09 UTC, dmyios approved these changes

2023-06-09 07:14 UTC, smau-centreon requested changes

2023-06-09 07:14 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur lors d'une tentative de mise à jour d'un panneau d'un tableau de bord qui appartient à un autre tableau de bord"
```suggestion
msgstr "Erreur lors d'une tentative de mise à jour d'un panneau de tableau de bord qui appartient à un autre tableau de bord"
```

2023-06-09 07:16 UTC, smau-centreon commented
For this message "Error while trying to update a dashboard panel which belongs to another dashboard". I was hesitating about the "panel" term (panel or widget?) but as it is message for the back-end side, that can be clarified later.

2023-06-09 07:35 UTC, smau-centreon approved these changes

2023-06-09 09:05 UTC, dmyios approved these changes

2023-06-09 09:11 UTC, jeremyjaouen approved these changes

2023-06-09 13:04 UTC, merged