feat(UI): List users roles
centreon/centreon pull request #1608
Opened 2023-06-08 11:58 UTC by Thebarda

## Description

This adds a modal that list users roles for a dashboard.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-06-08 12:58 UTC, bdauria approved these changes

2023-06-08 13:39 UTC, smau-centreon requested changes

2023-06-08 13:39 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Users roles"
```suggestion
# msgid "User roles"
```

2023-06-08 13:39 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Users roles"
```suggestion
# msgid "User roles"
```

2023-06-08 13:39 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Users roles"
```suggestion
# msgid "User roles"
```

2023-06-08 13:48 UTC, smau-centreon requested changes

2023-06-08 13:48 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Rôle utilisateurs"
```suggestion
msgstr "Rôles utilisateur"
```

2023-06-08 16:05 UTC, smau-centreon approved these changes

2023-06-09 10:09 UTC, g10 approved these changes
LGTM the 2 minor details can be addressed later

2023-06-09 10:29 UTC, Thebarda commented on centreon/packages/ui/src/components/List/ItemText.tsx
> +import { ListItemText } from '@mui/material';
Done

2023-06-09 13:06 UTC, g10 approved these changes

2023-06-27 19:21 UTC, merged