feat(APIv2): refacto
centreon/centreon pull request #1704
Opened 2023-06-21 16:03 UTC by abuathier

## Description

Jira: 🏷️ **MON-19394**

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-06-22 07:13 UTC, abuathier commented on centreon/src/Core/User/Application/Model/UserThemeConverter.php
> +            default => UserTheme::Dark,
Light by dfault.

2023-06-22 07:16 UTC, abuathier commented on centreon/src/Core/User/Application/Model/UserThemeConverter.php
> +    public static function toString(UserTheme $density): string
`$density` -> `$theme`

2023-06-22 13:16 UTC, smau-centreon requested changes

2023-06-23 08:14 UTC, dmyios approved these changes

2023-06-26 07:06 UTC, dmyios approved these changes

2023-06-26 07:14 UTC, callapa approved these changes

2023-06-26 08:02 UTC, smau-centreon approved these changes

2023-06-26 16:25 UTC, merged