feat: is_cloud_platform flag on versions endpoint
centreon/centreon pull request #1763
Opened 2023-06-26 17:36 UTC by g10

🔖 MON-20233

2023-06-26 18:06 UTC, jeremyjaouen requested changes

2023-06-26 18:06 UTC, jeremyjaouen commented on centreon/src/Centreon/Application/Controller/PlatformController.php
> +                'is_cloud_platform' => $_SERVER['IS_CLOUD_PLATFORM'] || false
It should be injected through Dependency Injection from configuration instead of using global $_SERVER. I can show you how to do that

2023-06-27 06:34 UTC, jeremyjaouen requested changes

2023-06-27 06:34 UTC, jeremyjaouen commented on centreon/doc/API/centreon-api-v23.10.yaml
> +
```suggestion
```
not needed for a boolean type

2023-06-28 07:17 UTC, jeremyjaouen requested changes

2023-06-28 07:17 UTC, jeremyjaouen commented on centreon/src/Centreon/Application/Controller/PlatformController.php
> +                'feature_flags' => (object) array_filter($this->flags->getAll()),
```suggestion
                'is_cloud_platform' => $this->flags->isCloudPlatform(),
```

It should be rediscussed on the process to handle correctly this needed

2023-06-28 08:03 UTC, a-launois commented on centreon/tests/api/features/PlatformVersions.feature
> +        And the JSON node "feature_flags" should exist
```suggestion
```

2023-06-28 08:17 UTC, a-launois approved these changes

2023-06-28 08:34 UTC, wtermellil approved these changes

2023-06-28 08:35 UTC, dmyios approved these changes

2023-06-28 09:04 UTC, jeremyjaouen approved these changes

2023-06-28 10:28 UTC, abuathier approved these changes

2023-06-28 10:29 UTC, merged