Mon 20286 dashboard api users search
centreon/centreon pull request #1784
Opened 2023-06-29 09:07 UTC by abuathier

## Description

> Two new endpoints
> `GET /configuration/dashboards/contacts `
> `GET /configuration/dashboards/contactsgroups`

Jira: 🏷️ **MON-20286**

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-06-29 12:55 UTC, jeremyjaouen commented
Is this possible to split this into 2 PRs (one by endpoint ?) Or there is too many shared code ?

2023-06-30 07:20 UTC, jeremyjaouen requested changes

2023-06-30 07:20 UTC, jeremyjaouen commented on centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
> +                $users = $this->readContactGroupRepository->findAll();
We should discuss with product team if we should manage contactgroup ACL to get this listing

2023-07-04 15:34 UTC, a-launois approved these changes

2023-07-05 06:46 UTC, jeremyjaouen submitted a review, later dismissed

2023-07-05 12:44 UTC, callapa commented on centreon/src/Core/Dashboard/Application/UseCase/FindDashboardContactGroups/FindDashboardContactGroups.php
> +    public function __invoke(FindDashboardContactGroupsPresenterInterface $presenter): void
Logs are missing.

2023-07-05 12:56 UTC, callapa approved these changes

2023-07-05 15:35 UTC, a-launois approved these changes

2023-07-05 15:46 UTC, merged