fix(php-cs-fixer): update of PhpCsFixerRuleSet
centreon/centreon pull request #1883
Opened 2023-07-12 15:05 UTC by abuathier

## Description

Jira: 🏷️ MON-171226

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

GitHub CI

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-07-13 11:42 UTC, callapa commented on centreon/src/Core/Domain/Configuration/Model/MetaService.php
> +     *                               1 - In SQL matching mode, specify a search string to be used in an SQL query.
Not sure we should keep this rule 🤔
In addition, the 120-character limit per line is not respected.

2023-07-13 12:53 UTC, tuntoja requested changes
Add a condition to not trigger this job on workflow runs carried by stable branches.

2023-07-13 12:53 UTC, tuntoja commented on .github/workflows/web.yml
> +    needs: [changes]
```suggestion
    needs: [changes, get-version]
```

2023-07-13 12:53 UTC, tuntoja commented on .github/workflows/web.yml
> +    if: ${{ needs.changes.outputs.has_backend_changes == 'true' }}
```suggestion
    if: ${{ needs.changes.outputs.has_backend_changes == 'true' && needs.get-version.outputs.stability != 'stable' }}
```

2023-07-17 07:18 UTC, abuathier commented on .github/workflows/web.yml
> +        run: vendor/bin/php-cs-fixer fix --verbose --dry-run
```suggestion
        run: vendor/bin/php-cs-fixer fix --verbose --dry-run --diff
```

2023-07-17 07:40 UTC, callapa submitted a review, later dismissed

2023-07-17 08:14 UTC, adr-mo submitted a review, later dismissed

2023-07-17 08:36 UTC, kduret approved these changes

2023-07-17 08:37 UTC, tuntoja approved these changes

2023-07-17 08:43 UTC, adr-mo approved these changes

2023-07-17 09:10 UTC, callapa approved these changes

2023-07-17 09:15 UTC, merged