Fix(upgrade): Field 'app_key' doesn't have a default value QUERY : INSERT INTO remote_servers
centreon/centreon pull request #199
Opened 2022-11-15 10:51 UTC by emabassi-ext

## Description

 fix the initial error (Field 'app_key' doesn't have a default value QUERY : INSERT INTO remote_servers) for > 22.04.6

**Fixes** # MON-15744

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [x] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

1. Upgrade a Centreon platform from version < 22.04.6
2. Create a Remote Server using wizard
3. Check that Remote Server is created without SQL errors

 

1. Install a Centreon platform with 22.04.x version
2. Create a Remote Server using wizard
3. Check that Remote Server is created without SQL errors

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-11-17 08:55 UTC, abuathier requested changes

2022-11-17 08:55 UTC, abuathier commented on centreon/www/install/php/Update-22.04.8.php
> +
Missing commit
```suggestion

    $pearDB->commit();
```

2022-11-17 08:55 UTC, abuathier commented on centreon/www/install/php/Update-22.04.8.php
> +        $pearDB->query("ALTER TABLE `remote_servers` DROP COLUMN `app_key`");
Indentation is not ok
```suggestion
    $pearDB->beginTransaction();
    $pearDB->query("ALTER TABLE `remote_servers` DROP COLUMN `app_key`");
```

2022-11-29 08:34 UTC, dmyios approved these changes

2022-11-30 08:00 UTC, merged