feat(Widget): Create foundations for the graph widget
centreon/centreon pull request #2003
Opened 2023-08-03 09:31 UTC by Thebarda

## Description

This implements the metrics data selection system for the graph widget

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-08-04 07:42 UTC, bdauria submitted a review, later dismissed

2023-08-07 13:32 UTC, bdauria submitted a review, later dismissed

2023-08-09 07:01 UTC, bdauria submitted a review, later dismissed

2023-08-10 08:07 UTC, dmyios approved these changes

2023-08-14 07:28 UTC, dmyios approved these changes

2023-08-14 07:58 UTC, bdauria approved these changes

2023-08-17 07:42 UTC, smau-centreon requested changes

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The limit of 2 units has been reached"
```suggestion
# msgid "You have reached the limit of 2 units"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "Host template required in service group association is not linked to service template"
```suggestion
#  msgid "Host template required in service group association is not linked to the service template"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "Host template required in service group association is not linked to service template"
```suggestion
msgid "Host template required in service group association is not linked to the service template"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "The limit of 2 units has been reached"
```suggestion
msgid "You have reached the limit of 2 units"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La limite de 2 unités a été atteinte"
```suggestion
msgstr "Vous avez atteint la limite de 2 unités"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "Host template required in service group association is not linked to service template"
```suggestion
#  msgid "Host template required in service group association is not linked to the service template"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The limit of 2 units has been reached"
```suggestion
# msgid "You have reached the limit of 2 units"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "Host template required in service group association is not linked to service template"
```suggestion
#  msgid "Host template required in service group association is not linked to the service template"
```

2023-08-17 07:42 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The limit of 2 units has been reached"
```suggestion
# msgid "You have reached the limit of 2 units"
```

2023-08-17 07:44 UTC, Thebarda commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The limit of 2 units has been reached"
Same comment as the previous PR

2023-08-17 07:44 UTC, Thebarda commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La limite de 2 unités a été atteinte"
Same comment as the previous PR

2023-08-17 07:52 UTC, smau-centreon approved these changes

2023-08-17 08:27 UTC, merged