[WIP] enh(dashboard): enhance arch of dashboard metrics data endpoint
centreon/centreon pull request #2012
Opened 2023-08-08 11:40 UTC by jeremyjaouen

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-08-09 08:38 UTC, jeremyjaouen commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/RealTimeDataInformation.php
> +     * @param privatereadonly?float $averageValue
```suggestion
     * @param float|null $lastValue
     * @param float|null $averageValue
```

2023-08-09 09:34 UTC, jeremyjaouen commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Le type de valeur dans le tableau ne sont pas [%s]"
```suggestion
```

2023-08-09 09:35 UTC, jeremyjaouen commented on centreon/src/Centreon/Domain/Common/Assertion/AssertionException.php
> +        return new self(sprintf(_('values type in the array are not [%s]'), $type), self::INVALID_CHOICE, $propertyPath);
```suggestion
        return new self(sprintf('values type in the array are not [%s]', $type), self::INVALID_CHOICE, $propertyPath);
```

2023-08-09 09:36 UTC, smau-centreon approved these changes

2023-08-10 07:14 UTC, dmyios submitted a review, later dismissed

2023-08-10 10:08 UTC, a-launois requested changes

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/DataSource.php
> +        private readonly ?int $minimum,
No default values ?

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/GeneralInformation.php
> +        private readonly int $indexId,
No default values ?

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/MetricInformation.php
> +        private readonly GeneralInformation $generalInformation,
No default values ?

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/RealTimeDataInformation.php
> +        private readonly array $values,
No default values ?

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/RealTimeDataInformation.php
> +     *
```suggestion
```

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/RealTimeDataInformation.php
> +     */
missing `@throws`

2023-08-10 10:08 UTC, a-launois commented on centreon/src/Core/Metric/Domain/Model/MetricInformation/ThresholdInformation.php
> +        private readonly ?float $warningThreshold,
No default values ?

2023-08-10 12:07 UTC, a-launois approved these changes

2023-08-10 12:08 UTC, dmyios approved these changes

2023-08-10 12:09 UTC, smau-centreon approved these changes

2023-08-10 12:41 UTC, merged