Fix(MON-21040): ‎centreon/www/class/centreonLogAction.class.php
centreon/centreon pull request #2065
Opened 2023-08-25 10:42 UTC by Exodiaaaa

## Description
Fix on ‎centreon/www/class/centreonLogAction.class.php

**Fixes** # (MON-21040)

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Given a user editing/creating/deleting a resources (host, HTPL, service, HTPL)
When he access to “Administration > Logs”
He can see the change

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-08-29 15:58 UTC, dmyios requested changes

2023-08-29 15:58 UTC, dmyios commented on centreon/www/class/centreonLogAction.class.php
>          }
**Now**: You're inserting one line into DB and bind the last `$key` & `$value` of `$fields` array to the query
**Before**: The number of lines inserted into DB equals to the length of `$fields` array.

Please re-check your algorithm.

2023-08-30 07:38 UTC, dmyios commented on centreon/www/class/centreonLogAction.class.php
>          }
```suggestion
        $values = [];
        $index = 0;
        foreach ($fields as $field_key => $field_value) {
            $values[] = '(:field_key_' . $index . ', :field_value_' . $index . ', :logId)';
            $index++;
        }
```

2023-08-30 07:40 UTC, dmyios commented on centreon/www/class/centreonLogAction.class.php
> +        }
```suggestion
        $statement = $pearDBO->prepare($query);
        $index = 0;
        foreach ($fields as $field_key => $field_value) {
            $key = CentreonDB::escape($field_key);
            $value = CentreonDB::escape($field_value);
            $statement->bindValue(':field_key_' . $index, $key);
            $statement->bindValue(':field_value_' . $index, $value);
            $statement->bindValue(':logId', $logId, PDO::PARAM_INT);
            $index++;
        }
```

2023-08-30 08:50 UTC, callapa approved these changes

2023-08-30 08:58 UTC, dmyios approved these changes

2023-08-30 09:51 UTC, merged