enh(UI): Handle range thresholds on widgets
centreon/centreon pull request #2122
Opened 2023-09-04 14:27 UTC by Thebarda

## Description

This handles range thresholds on widgets

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-09-06 15:54 UTC, smau-centreon requested changes

2023-09-06 15:54 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Value customized"
```suggestion
# msgid "Custom value"
```

2023-09-06 15:54 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Value customized"
```suggestion
# msgid "Custom value"
```

2023-09-06 15:54 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgstr "Les 28 précédents jours"
```suggestion
msgstr "Les 28 derniers jours"
```

2023-09-06 15:54 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Value customized"
```suggestion
# msgid "Custom value"
```

2023-09-06 15:54 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Value customized"
```suggestion
# msgid "Custom value"
```

2023-09-07 11:57 UTC, smau-centreon requested changes

2023-09-07 11:57 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "Last 12 Hours"
```suggestion
msgid "Last 12 hours"
```

2023-09-07 11:57 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "Last 5 Days"
### 
```suggestion
msgid "Last 5 days"
```

2023-09-07 11:57 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "Last 28 Days"
```suggestion
msgid "Last 28 days"
```

2023-09-07 12:10 UTC, SoldierBoy31 approved these changes

2023-09-07 12:17 UTC, jeremyjaouen approved these changes

2023-09-07 12:31 UTC, smau-centreon approved these changes

2023-09-07 12:38 UTC, merged