enh(UI): Apply feedbacks about widget form
centreon/centreon pull request #2165
Opened 2023-09-13 09:03 UTC by Thebarda

## Description

This PR applies feedbacks from the previous sprint review during this summer.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-09-14 14:13 UTC, bdauria submitted a review, later dismissed

2023-09-15 08:01 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Bar"
```suggestion
# msgid "Bar chart"
```

2023-09-15 08:01 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The default value is the value defined for the first metric used"
```suggestion
# msgid "The default value is the value defined for the first metric used."
```

2023-09-15 08:01 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You can choose only one resource for each resource type"
```suggestion
# msgid "You can choose only one resource for each resource type."
```

2023-09-15 08:02 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
# msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-15 08:03 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "You are not allowed to add a service"
```suggestion
#  msgid "You are not allowed to add a service."
```

2023-09-15 08:03 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "'%s' service name already exists for host ID %d"
```suggestion
#  msgid "'%s' service name already exists for host ID %d."
```

2023-09-15 08:05 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
>  #  msgid "'%s' service name already exists for host ID %d"
```suggestion
#  msgid "'%s' service name already exists for host ID %d."
```

2023-09-15 08:05 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Bar"
```suggestion
# msgid "Bar chart"
```

2023-09-15 08:05 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "The default value is the value defined for the first metric used"
```suggestion
# msgid "The default value is the value defined for the first metric used."
```

2023-09-15 08:06 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You can choose only one resource for each resource type"
```suggestion
# msgid "You can choose only one resource for each resource type."
```

2023-09-15 08:26 UTC, bdauria approved these changes

2023-09-15 09:40 UTC, smau-centreon requested changes

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>  export const labelAddWidget = 'Add widget';
```suggestion
export const labelAddWidget = 'Add a widget';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>    'Select a widget type to activate the preview';
```suggestion
  'Select a widget type to activate the preview';
```
```suggestion
  'Select a widget type to activate the preview.';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
> +  'By turning off this option, all links included in the widget will be opened in the same tab';
```suggestion
  'By turning off this option, all links included in the widget will be opened in the same tab.';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>  export const labelDeleteAWidget = 'Delete a widget';
```suggestion
export const labelDeleteAWidget = 'Delete widget';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>  export const labelAddResource = 'Add resource';
```suggestion
export const labelAddResource = 'Add a resource';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>  export const labelAddMetric = 'Add metric';
```suggestion
export const labelAddMetric = 'Add a metric';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
>    'Thresholds are automatically hidden if you select 2 metric units';
```suggestion
  'Thresholds are automatically hidden if you select 2 metric units.';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
> +export const labelBar = 'Bar';
```suggestion
export const labelBar = 'Bar chart';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
> +  'The default value is the value defined for the first metric used';
```suggestion
  'The default value is the value defined for the first metric used.';
```

2023-09-15 09:40 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboard/translatedLabels.ts
> +  'You can choose only one resource for each resource type';
```suggestion
  'You can choose only one resource for each resource type.';
```

2023-09-15 15:29 UTC, smau-centreon approved these changes

2023-09-18 07:04 UTC, SoldierBoy31 approved these changes

2023-09-18 07:59 UTC, bdauria approved these changes

2023-09-18 09:03 UTC, merged