Mon 21543 implement top bottom widget
centreon/centreon pull request #2175
Opened 2023-09-15 07:39 UTC by Thebarda

## Description

This implements the top bottom widget.

https://github.com/centreon/centreon/assets/12515407/e2f13014-1e35-4610-b768-826e8da00681

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-09-22 08:31 UTC, Noha-ElAbrouki submitted a review, later dismissed

2023-09-25 07:36 UTC, SoldierBoy31 commented on centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as critical when the critical threshold is customized.snap.png
Is it normal that the component is not centered on the page ?

2023-09-25 07:39 UTC, Thebarda commented on centreon/cypress/visual-testing-snapshots/www/widgets/src/centreon-widget-singlemetric/src/SingleMetric.cypress.spec.tsx/Single metric Widget -- Single bar -- displays the metric value as critical when the critical threshold is customized.snap.png
Yes it's normal bc I haven't defined the width of the container which is defined in the widget

2023-09-25 07:47 UTC, SoldierBoy31 approved these changes

2023-09-25 08:08 UTC, smau-centreon requested changes

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
# msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
# msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "En désactivant cette option, tous les liens inclus dans le widget seront ouverts dans le même onglet"
```suggestion
msgstr "En désactivant cette option, tous les liens inclus dans le widget seront ouverts dans le même onglet."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "By turning off this option, all the links included in the widget will be opened in the same tab"
```suggestion
msgid "By turning off this option, all the links included in the widget will be opened in the same tab."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "En désactivant cette option, tous les liens inclus dans le widget seront ouverts dans le même onglet"
```suggestion
msgstr "En désactivant cette option, tous les liens inclus dans le widget seront ouverts dans le même onglet."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
# msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-25 08:08 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "By turning off this option, all links included in the widget will be opened in the same tab"
```suggestion
# msgid "By turning off this option, all links included in the widget will be opened in the same tab."
```

2023-09-25 08:29 UTC, SoldierBoy31 approved these changes

2023-09-25 09:01 UTC, callapa approved these changes

2023-09-26 07:47 UTC, smau-centreon approved these changes

2023-09-26 07:56 UTC, merged