enh(monitoring): deletions of monitoring pages for next major message
centreon/centreon pull request #2278
Opened 2023-10-02 15:07 UTC by adr-mo

🏷️ MON-22082

This PR intends to alert on the deletion of monitoring pages for next major version (24.04)

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Message should be changed (see ticket)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-10-02 15:32 UTC, dmyios submitted a review, later dismissed

2023-10-02 15:37 UTC, a-launois submitted a review, later dismissed

2023-10-03 07:18 UTC, smau-centreon requested changes

2023-10-03 07:18 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "[Page dépréciée] Cette page sera supprimée dans la prochaine version majeure. Utilisez la nouvelle page: "
```suggestion
msgstr "[Page dépréciée] Cette page sera supprimée dans la prochaine version majeure. Veuillez utiliser la nouvelle page : "
```

2023-10-03 08:33 UTC, smau-centreon approved these changes

2023-10-03 08:42 UTC, dmyios approved these changes

2023-10-03 08:43 UTC, merged