enh(UI): Global UI feedbacks on dashboard
centreon/centreon pull request #2287
Opened 2023-10-03 16:12 UTC by Thebarda

## Description

This integrates small changes that improves UX on dashboard

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-10-03 16:30 UTC, bdauria submitted a review, later dismissed

2023-10-03 18:59 UTC, Noha-ElAbrouki approved these changes

2023-10-05 07:47 UTC, bdauria submitted a review, later dismissed

2023-10-06 07:29 UTC, smau-centreon requested changes

2023-10-06 07:29 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "voir les propriétés du widget"
```suggestion
msgstr "Voir les propriétés du widget"
```

2023-10-06 07:32 UTC, Thebarda commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Welcome to the dashboard interface!"
I told you that I will change in the wording adjustments PR

2023-10-06 09:08 UTC, Noha-ElAbrouki approved these changes

2023-10-06 09:32 UTC, merged