enh(centreon-php): add service to the search of 'monitoring/hostgroups' endpoint
centreon/centreon pull request #2343
Opened 2023-10-11 08:09 UTC by Yassir-BenBOUBKER

for the bulk mode tasks ( MAP )
we need Service to be added to the Search (service.display_name) In Host Groups / service groups

especially since the Doc 
https://docs-api.centreon.com/api/centreon-web/23.04/#tag/Host-group/paths/~1monitoring~1hostgroups/

supports this feature but it doesn’t work for real in the API

2023-10-11 08:29 UTC, a-launois commented on centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
> +        $ServiceConcordanceArray = [
```suggestion
        $serviceConcordanceArray = [
```

2023-10-11 08:30 UTC, a-launois commented on centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
> +            $hostGroupConcordanceArray = array_merge($hostGroupConcordanceArray, $ServiceConcordanceArray);
```suggestion
        if (count(array_intersect($searchParameters, array_keys($serviceConcordanceArray))) > 0) {
            $shouldJoinService = true;
            $hostGroupConcordanceArray = array_merge($hostGroupConcordanceArray, $serviceConcordanceArray);
```

2023-10-11 08:38 UTC, adr-mo requested changes

2023-10-11 08:38 UTC, a-launois submitted a review, later dismissed

2023-10-11 08:38 UTC, adr-mo commented on centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
> +        ];
PHP uses camelCase for varirable definitions
```suggestion
        $serviceConcordanceArray = [
            'service.display_name' => 'srv.display_name',
        ];
```

2023-10-11 08:38 UTC, adr-mo commented on centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
> +        }
```suggestion
        if (count(array_intersect($searchParameters, array_keys($serviceConcordanceArray))) > 0) {
            $shouldJoinService = true;
            $hostGroupConcordanceArray = array_merge($hostGroupConcordanceArray, $serviceConcordanceArray);
        }
```

2023-10-11 08:41 UTC, adr-mo submitted a review, later dismissed

2023-10-11 12:45 UTC, wtermellil submitted a review, later dismissed

2023-10-11 12:51 UTC, adr-mo approved these changes

2023-10-11 14:17 UTC, callapa requested changes
Please update the API documentation

2023-10-12 16:22 UTC, callapa submitted a review, later dismissed

2023-10-12 16:29 UTC, callapa commented on centreon/src/Centreon/Infrastructure/Monitoring/MonitoringRepositoryRDB.php
> +            'host.display_name' => 'h.display_name',
Property not referenced in the API documentation

2023-10-13 07:11 UTC, callapa approved these changes

2023-10-13 07:58 UTC, adr-mo approved these changes

2023-10-13 10:38 UTC, merged