Fix(security): Sanitize and binding queries
centreon/centreon pull request #239
Opened 2022-11-20 22:10 UTC by hyahiaoui-ext

## Description

Sanitizing and binding queries

**Fixes** # MON-15367

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [x] 22.04.x
- [x] 22.10.x
- [x] 23.04.x (master)

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-11-21 09:36 UTC, a-launois requested changes

2022-11-21 09:36 UTC, a-launois commented on centreon/www/include/configuration/configObject/host_categories/listHostCategories.php
> +if ($search !== '') {
same as previous comment

2022-11-25 08:49 UTC, dmyios approved these changes

2022-11-25 09:03 UTC, a-launois approved these changes

2022-12-15 14:41 UTC, merged