enh(LDAP):  filter syntax validation method appears erroneous
centreon/centreon pull request #2432
Opened 2023-10-23 11:32 UTC by cbadr-ext

## Description

Impossible to save the ldap form because of filter syntax error : 

**Fixes** # (MON-21663)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Login to the Centreon Platform

Go to Administration  >  Parameters  >  LDAP > edit the ldap config

Set this filter (&(samAccountName=%s)(objectClass=user)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))

And you should get an error syntax

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-10-23 15:43 UTC, abuathier requested changes

2023-10-23 15:45 UTC, cbadr-ext commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +        && preg_match('/.*/', $filterValue);
![image](https://github.com/centreon/centreon/assets/134523914/32ee0b90-cd19-4dfb-bb6d-fa722f0deb00)

2023-10-23 15:47 UTC, cbadr-ext commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +        && preg_match('/.*/', $filterValue);
i see it in the ticket but if possible can i remove it ?

2023-10-23 15:56 UTC, cbadr-ext commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +        && preg_match('/.*/', $filterValue);
i agree if i rmove it will be perfect

2023-10-24 08:24 UTC, abuathier approved these changes

2023-10-24 08:25 UTC, dmyios approved these changes

2023-10-24 10:00 UTC, merged