fix(event-logs) : issue with pagination displayed without results fixed
centreon/centreon pull request #2448
Opened 2023-10-24 14:51 UTC by Exodiaaaa

## Description

When I try to display Event log about Hostgroups, the result table is empty, but I see a pagination with 11 entries !

**Fixes** # (MON-21964)

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Create a host group then go check event logs

Result:
List of events if exist or a empty list if nothing exist

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-10-25 07:06 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/xml/data.php
> +    {
```suggestion
    if ($rows > $limit) {
```

2023-10-25 08:48 UTC, dmyios submitted a review, later dismissed

2023-10-25 09:27 UTC, abuathier requested changes
There is something not clair to me in this fix about the moved `$rows = $stmt->rowCount();`

Because the number of rows can change when we pass inside the if which execute again the query with a modified offset.

2023-10-25 13:44 UTC, Exodiaaaa commented
> There is something not clair to me in this fix about the moved `$rows = $stmt->rowCount();`
> 
> Because the number of rows can change when we pass inside the `if` which execute again the query with a modified offset.

> the row count doesnt change its the same for both cases so its no probleme for moving the `$stmt->rowCount()` on top it doesnt impact anything

2023-10-27 14:23 UTC, abuathier submitted a review, later dismissed

2023-10-31 09:14 UTC, a-launois approved these changes

2023-11-02 09:39 UTC, merged