enh(event logs): add possibility to display ack dt comments notifications event handler
centreon/centreon pull request #2624
Opened 2023-11-16 09:28 UTC by cbadr-ext

## Description

add a filter for ACK et NOTIF rather than teaking the request on other parameters.

CSV export should not been forgotten

**Fixes** # (MON-14623)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [ ] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

add a filter for ACK et NOTIF

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-11-27 08:12 UTC, jeremyjaouen requested changes

2023-11-27 08:12 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Formatter.php
> +    private string $notif = '';
```suggestion
    private string $acknowledgement = '';
    private string $notifification = '';
```

Please avoid shortname into variable name to keep it understandable

2023-11-27 08:12 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Formatter.php
> +    }
same here

2023-11-27 08:12 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Formatter.php
> +            ['Service', 'Ok', 'Warning', 'Critical', 'Unknown', 'Ack', 'Notif'],
```suggestion
            ['Service', 'Ok', 'Warning', 'Critical', 'Unknown', 'Acknowledgement', 'Notification'],
```

2023-11-27 08:12 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/QueryGenerator.php
> +    private string $notif;
same here

2023-11-27 08:12 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/QueryGenerator.php
> +
same here

2023-11-30 08:11 UTC, jeremyjaouen requested changes

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/xml/data.php
> +    array_push($svc_msg_status_set, "'" . STATUS_ACKNOWLEDGEMRNT . "'");
```suggestion
    array_push($svc_msg_status_set, "'" . STATUS_ACKNOWLEDGEMENT . "'");
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/xml/data.php
> +    STATUS_ACKNOWLEDGEMRNT => 'service_acknowledgement',
```suggestion
    STATUS_ACKNOWLEDGEMENT => 'service_acknowledgement',
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Request.php
> +        if ($this->getNotif() === 'true') {
```suggestion
        if ($this->getNotification() === 'true') {
```

PHP Error: Undefined method getNotif

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Formatter.php
> +    public function setAck(string $acknowledgement): void
```suggestion
    public function setAcknowledgement(string $acknowledgement): void
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/QueryGenerator.php
> +    public function setAck(string $acknowledgement): void
```suggestion
    public function setAcknowledgement(string $acknowledgement): void
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Request.php
> +    public function getAck(): string
```suggestion
    public function getAcknowledgement(): string
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/Request.php
> +        if ($this->getAck() === 'true') {
```suggestion
        if ($this->getAcknowledgement() === 'true') {
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/export/data.php
> +$queryGenerator->setAck($requestHandler->getAck());
```suggestion
$queryGenerator->setAcknowledgement($requestHandler->getAck());
```

2023-11-30 08:11 UTC, jeremyjaouen commented on centreon/www/include/eventLogs/xml/data.php
> +define("STATUS_ACKNOWLEDGEMRNT", 5);
```suggestion
define("STATUS_ACKNOWLEDGEMENT", 5);
```

2023-12-06 08:05 UTC, jeremyjaouen approved these changes

2024-01-02 16:02 UTC, callapa commented on centreon/www/include/eventLogs/export/Request.php
> +    private string $acknowledgement = 'true';
Why delete the $notification variable?

2024-01-12 08:07 UTC, jeremyjaouen approved these changes

2024-01-12 08:27 UTC, dmyios approved these changes

2024-01-26 12:05 UTC, merged