enh(UI): Uniformize metric selection
centreon/centreon pull request #2647
Opened 2023-11-18 21:41 UTC by Thebarda

## Description

This uniformizes the metric selection in order to get the same metric selection system in both graph, top bottom and single metric

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-11-20 11:35 UTC, Med1233 approved these changes

2023-11-20 12:34 UTC, MedWassCh submitted a review, later dismissed

2023-11-21 08:16 UTC, bdauria submitted a review, later dismissed

2023-11-21 10:24 UTC, Med1233 submitted a review, later dismissed

2023-11-24 09:52 UTC, Med1233 submitted a review, later dismissed

2023-11-27 09:17 UTC, bdauria submitted a review, later dismissed

2023-11-28 13:00 UTC, Med1233 approved these changes

2023-11-28 16:15 UTC, smau-centreon requested changes

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You must add resources to filter on a single metric."
```suggestion
# msgid "Refine your filter on a single metric by adding more resources."
```

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Vous devez ajouter des ressources afin de filtrer sur une seule métrique."
```suggestion
msgstr "Affinez votre filtre sur une seule métrique en ajoutant d'autres ressources."
```

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You must add resources to filter on a single metric."
```suggestion
# msgid "Refine your filter on a single metric by adding more resources."
```

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "You must add resources to filter on a single metric."
```suggestion
msgid "Refine your filter on a single metric by adding more resources."
```

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You must add resources to filter on a single metric."
```suggestion
# msgid "Refine your filter on a single metric by adding more resources."
```

2023-11-28 16:15 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You must add resources to filter on a single metric."
```suggestion
# msgid "Refine your filter on a single metric by adding more resources."
```

2023-11-29 08:05 UTC, kduret approved these changes
ok for cypress e2e changes

2023-11-29 12:44 UTC, smau-centreon approved these changes

2023-11-29 15:58 UTC, Med1233 approved these changes

2023-11-29 16:41 UTC, merged