[enh](ldap): add ldap connection timeout to avoid infinite connection
centreon/centreon pull request #271
Opened 2022-11-22 14:03 UTC by emabassi-ext

## Description

add default connection-timeout value to avoid infinit loop

Also the hard coded timeout should be a parameter that can be defined in the LDAP form

**Fixes** # MON-3511

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

1. Go to ‘Administration > Parameters > LDAP’
2. Add an incorrect LDAP configuration (host or port) but enable it with timeout value (5 for example)
3. Check /var/log/centreon/ldap.log
4. Try to connect with login/user
5. Check in log that a timeout is this defined (5 seconds)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-11-29 08:13 UTC, dmyios submitted a review, later dismissed

2022-12-12 08:38 UTC, jeremyjaouen requested changes

2022-12-12 08:38 UTC, jeremyjaouen commented on centreon/www/class/centreonLDAP.class.php
> +        if (!empty($dbConnectionTimeout['ari_value'])) {
```suggestion
        if (! empty($dbConnectionTimeout['ari_value'])) {
```

2022-12-12 08:38 UTC, jeremyjaouen commented on centreon/www/class/centreonLDAP.class.php
> +            if (!empty($ldap['connection_timeout'])) {
```suggestion
            if (! empty($ldap['connection_timeout'])) {
```

2022-12-12 08:38 UTC, jeremyjaouen commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +    if (!preg_match('/=%s\)/', $filterValue)) {
```suggestion
    if (! preg_match('/=%s\)/', $filterValue)) {
```

2022-12-12 08:38 UTC, jeremyjaouen commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +    if (!preg_match('/^(\s*\((?:[&|](?1)+|(?:!(?1))|[a-zA-Z][a-zA-Z0-9-]*[<>~]?=[^()]*)\s*\)\s*)$/', $filterValue)) {
```suggestion
    if (! preg_match('/^(\s*\((?:[&|](?1)+|(?:!(?1))|[a-zA-Z][a-zA-Z0-9-]*[<>~]?=[^()]*)\s*\)\s*)$/', $filterValue)) {
```

2022-12-27 10:05 UTC, jeremyjaouen approved these changes

2022-12-27 10:13 UTC, kduret commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +    if (! preg_match('/=%s\)/', $filterValue)) {
```suggestion
{
    if (empty(trim($filterValue)) {
        return true;
    }

    if (! preg_match('/=%s\)/', $filterValue)) {
```

2022-12-27 10:13 UTC, kduret commented on centreon/www/include/Administration/parameters/DB-Func.php
> +            : "NULL"
```suggestion
        htmlentities($ret["ldap_connection_timeout"], ENT_QUOTES, "UTF-8")
```

2023-01-04 12:51 UTC, abuathier commented on centreon/www/include/Administration/parameters/ldap/DB-Func.php
> +    return true;
Why not simplier ?
```suggestion
    return preg_match('/=%s\)/', $filterValue)
        && preg_match('/^(\s*\((?:[&|](?1)+|(?:!(?1))|[a-zA-Z][a-zA-Z0-9-]*[<>~]?=[^()]*)\s*\)\s*)$/', $filterValue);
```

2023-01-17 08:13 UTC, kduret commented on centreon/www/install/php/Update-22.10.0-beta.1.php
>      $errorMessage = "Unable to delete 'appKey' information from database";
move upgrade script to 23.04.0-beta.1

2023-01-17 08:15 UTC, kduret commented on centreon/www/install/php/Update-22.10.0-beta.1.php
> +        (SELECT ar_id, 'ldap_connection_timeout', '' FROM auth_ressource)"
add connection timeout to empty only if not exists

2023-01-18 15:21 UTC, abuathier submitted a review, later dismissed

2023-01-23 09:55 UTC, callapa approved these changes

2023-01-23 10:22 UTC, smau-centreon requested changes

2023-01-23 10:22 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Bad LDAP filter syntax"
```suggestion
#  msgid "Incorrect LDAP filter syntax"
```

2023-01-23 10:22 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Bad LDAP filter syntax"
```suggestion
msgid "Incorrect LDAP filter syntax"
```

2023-01-23 10:22 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Bad LDAP filter syntax"
```suggestion
#  msgid "Mauvaise syntaxe du filtre LDAP"
```

2023-01-23 10:22 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Bad LDAP filter syntax"
```suggestion
#  msgid "Mauvaise syntaxe du filtre LDAP"
```

2023-01-26 11:26 UTC, jeremyjaouen approved these changes

2023-01-27 08:36 UTC, smau-centreon approved these changes

2023-01-27 08:36 UTC, merged