[WIP] feat(dashboards): implements an endpoint to update Playlist Shares
centreon/centreon pull request #2710
Opened 2023-11-27 10:13 UTC by jeremyjaouen

## Description

**Fixes** # MON-24896

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-11-27 14:30 UTC, jeremyjaouen commented on centreon/src/Core/Contact/Infrastructure/Repository/DbReadContactRepository.php
> +                contact_contact_id
```suggestion
                DISTINCT contact_contact_id
```

2023-11-28 08:06 UTC, dmyios commented on centreon/doc/API/v24.04/Configuration/Dashboard/Schema/Playlist/UpdatePlaylistShareRequest.yaml
> +  contactgroupss:
```suggestion
  contact_groups:
```

2023-11-28 08:13 UTC, dmyios requested changes

2023-11-28 08:13 UTC, dmyios commented on centreon/src/Core/Contact/Infrastructure/Repository/DbReadContactGroupRepository.php
> +            WHERE cg_id IN ( ' . implode(', ', array_keys($bind)) . ')'
Heredoc

2023-11-28 08:13 UTC, dmyios commented on centreon/src/Core/Contact/Infrastructure/Repository/DbReadContactRepository.php
> +            WHERE contact_id IN ( ' . implode(', ', array_keys($bind)) . ')'
Heredoc

2023-11-28 08:13 UTC, dmyios commented on centreon/src/Core/Dashboard/Playlist/Infrastructure/API/SharePlaylist/SharePlaylistSchema.json
> +        "contactgroups": {
```suggestion
        "contact_groups": {
```

2023-11-28 10:25 UTC, adr-mo commented on centreon/src/Core/Dashboard/Playlist/Application/UseCase/SharePlaylist/SharePlaylist.php
> +                $this->error('Access Forbidden');
IMHO this could be rephrased to give more context something like
`User does not have sufficient rigths to create a Playlist`

2023-11-28 10:25 UTC, adr-mo commented on centreon/src/Core/Dashboard/Playlist/Application/UseCase/SharePlaylist/SharePlaylist.php
> +            $contactGroupIds = array_map(fn(array $contactGroup): int => $contactGroup['id'], $request->contactGroups);
```suggestion
            $contactIds = array_map(fn (array $contact): int => $contact['id'], $request->contacts);
            $contactGroupIds = array_map(fn (array $contactGroup): int => $contactGroup['id'], $request->contactGroups);
```
Not sure if it was carved that a space must be added after `fn`

2023-11-28 10:29 UTC, adr-mo commented
@jeremyjaouen As fresh installation SQL script has been modified the `Update-24.04.0.php` should also be modified to include the new column

2023-11-28 12:27 UTC, adr-mo submitted a review, later dismissed

2023-11-28 12:28 UTC, dmyios submitted a review, later dismissed

2023-11-28 14:58 UTC, smau-centreon requested changes

2023-11-28 14:58 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "The following playlist does not exist: [%d]."
```suggestion
msgid "The following playlist does not exist: [%d]"
```

2023-11-28 14:58 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "The following contacts don't exist: [%s]"
```suggestion
msgid "The following contact does not exist: [%s]"
```

2023-11-28 14:58 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Les contacts suivant n'existent pas: [%s]"
```suggestion
msgstr "Le contact suivant n'existe pas : [%s]"
```

2023-11-29 08:03 UTC, dmyios approved these changes

2023-11-29 08:17 UTC, smau-centreon approved these changes

2023-11-29 08:31 UTC, merged