fix path transversal when user change default image
centreon/centreon pull request #294
Opened 2022-11-23 16:27 UTC by emabassi-ext

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-12-12 08:37 UTC, jeremyjaouen requested changes

2022-12-12 08:37 UTC, jeremyjaouen commented on centreon/www/include/configuration/configGenerate/xml/moveFiles.php
> +        $NagiosPathImg = basename($centreon->optGen["nagios_path_img"]);
```suggestion
        $nagiosPathImg = basename($centreon->optGen["nagios_path_img"]);
```

2022-12-12 08:44 UTC, wtermellil requested changes

2022-12-12 08:44 UTC, wtermellil commented on centreon/www/include/configuration/configGenerate/xml/moveFiles.php
> +        $NagiosPathImg = basename($centreon->optGen["nagios_path_img"]);
```suggestion
        $nagiosPathImg = basename($centreon->optGen["nagios_path_img"]);
```

2022-12-12 09:50 UTC, wtermellil approved these changes

2022-12-19 11:26 UTC, wtermellil approved these changes

2022-12-20 08:01 UTC, a-launois approved these changes

2022-12-21 09:30 UTC, jeremyjaouen approved these changes

2022-12-21 09:31 UTC, merged