fix(insertGraphTemplate): Update insertGraphTemplate function
centreon/centreon pull request #3007
Opened 2023-12-27 14:22 UTC by cbadr-ext

## Description

Update insertGraphTemplate function

**Fixes** # (MON-32704)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 22.04.x
- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-12-27 17:20 UTC, jeremyjaouen requested changes

2023-12-27 17:20 UTC, jeremyjaouen commented on centreon/www/include/views/graphTemplates/DB-Func.php
> +    $statement = $pearDB->prepare($rq);
This should be after concatenate the entire request

2023-12-28 12:46 UTC, jeremyjaouen approved these changes

2023-12-28 12:49 UTC, Exodiaaaa approved these changes

2023-12-28 13:08 UTC, merged