enh(UI): Add support for shares in dashboard list
centreon/centreon pull request #3078
Opened 2024-01-08 21:08 UTC by Thebarda

## Description

This adds the support of shares in the dashboard list

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-01-08 21:12 UTC, bdauria commented on centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
> +    it('revokes the acces right when a row is expanded and ', () => {
```suggestion
    it('revokes the access right when a row is expanded and the corresponding action is clicked ', () => {
```

2024-01-09 00:13 UTC, Med1233 commented on centreon/www/front_src/src/Dashboards/api/models.ts
> +}
Isn't this the same as the DashboardRole mentioned above ?

2024-01-09 00:13 UTC, Med1233 commented on centreon/www/front_src/src/Dashboards/api/models.ts
> +
Isn't this the same as the ContactType mentioned above

2024-01-09 08:25 UTC, smau-centreon requested changes

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard."
```suggestion
# msgid "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard."
```suggestion
# msgid "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard."
```suggestion
msgid "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Vous êtes sur le point de supprimer <strong>{{name}}</strong> de la liste des utilisateurs. Il/Elle n'aura plus accès au tableau de bord."
```suggestion
msgstr "Vous êtes sur le point de supprimer <strong>{{name}}</strong> de la liste des utilisateurs. Cet utilisateur n'aura plus accès au tableau de bord."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard."
```suggestion
# msgid "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard."
```suggestion
# msgid "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard."
```

2024-01-09 08:25 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/translatedLabels.tsx
> +  "You are going to delete <strong>{{name}}</strong> from the user list. He/She won't have access to the dashboard.";
```suggestion
  "You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard.";
```

2024-01-26 15:01 UTC, Med1233 approved these changes

2024-01-26 15:40 UTC, Med1233 approved these changes

2024-01-26 15:47 UTC, smau-centreon approved these changes

2024-01-26 15:47 UTC, merged