enh(UI): Add new time periods + fix wording/translations
centreon/centreon pull request #3110
Opened 2024-01-12 10:47 UTC by Thebarda

## Description

This add new time period entries on widgets and fix the wording and translations

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-02-01 20:53 UTC, L0th0mat1c approved these changes

2024-02-02 09:19 UTC, smau-centreon requested changes

2024-02-02 09:19 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Les dernières 24 heures"
```suggestion
msgstr "Les 24 dernières heures"
```

2024-02-02 14:11 UTC, smau-centreon approved these changes

2024-02-02 14:31 UTC, Med1233 approved these changes

2024-02-02 14:40 UTC, merged