enh (host): new API-type repositories for hosts
centreon/centreon pull request #3188
Opened 2024-01-26 14:51 UTC by callapa

## Description

🏷️ MON-21552

As part of the migration from an on-premises Centreon platform to a remote platform, we need to set up a new repository that allows us to retrieve hosts by making HTTP calls to the remote Centreon platform.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x (master)

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-01-29 16:37 UTC, adr-mo submitted a review, later dismissed

2024-01-30 08:24 UTC, a-launois requested changes

2024-01-30 08:24 UTC, a-launois commented on centreon/src/Core/Host/Application/Repository/ReadHostRepositoryInterface.php
> +     * Find hosts by their id.
```suggestion
     * Find hosts by their names.
```

2024-01-30 13:17 UTC, adr-mo approved these changes

2024-01-30 14:05 UTC, merged