enh(api) : add the posibility to search using host categories
centreon/centreon pull request #3207
Opened 2024-01-29 15:30 UTC by Exodiaaaa

## Description

Enhance endpoint GET: /configuration/hosts/groups by adding possibility to search by host categories

**Fixes** # (MON-34388)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [X] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

try to filter hostgroups using the new option on the filter : http://localhost:8080/centreon/api/v24.04/configuration/hosts/groups?search={"hostcategories_id":1}
You should create a hostcategorie to test it

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2024-01-29 20:14 UTC, jeremyjaouen commented
https://github.com/centreon/centreon/blob/19ba1aadc139e2f957c29c25ef385823bb0e1738/centreon/doc/API/centreon-api-v24.04.yaml#L664-L665

Can you also add the new search parameters in documentation ?

2024-01-30 10:41 UTC, Exodiaaaa commented
> https://github.com/centreon/centreon/blob/19ba1aadc139e2f957c29c25ef385823bb0e1738/centreon/doc/API/centreon-api-v24.04.yaml#L664-L665
> 
> Can you also add the new search parameters in documentation ?



> https://github.com/centreon/centreon/blob/19ba1aadc139e2f957c29c25ef385823bb0e1738/centreon/doc/API/centreon-api-v24.04.yaml#L664-L665
> 
> Can you also add the new search parameters in documentation ?

Done !

2024-01-31 15:18 UTC, adr-mo submitted a review, later dismissed
The request parameters allows to filter with multiple values for host category ids
Therefore:

The parameter should be named: `host_category_ids`

2024-01-31 16:04 UTC, Exodiaaaa commented
> The request parameters allows to filter with multiple values for host category ids Therefore:
> 
> The parameter should be named: `host_category_ids`

Done

2024-02-01 08:19 UTC, jeremyjaouen commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +            )
Is this necessary if the search parameter host_category_ids is not present ? 
If not add a check for this parameter before doing the appendJoin

2024-02-01 08:49 UTC, callapa commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +            'host_category_ids' => 'hc.hc_id',
```suggestion
            'host_category_id' => 'hc.hc_id',
```

2024-02-01 09:56 UTC, callapa submitted a review, later dismissed

2024-02-01 09:56 UTC, callapa commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +                        ON hcr.hostcategories_hc_id = hc.hc_id
You don't take ACLs into account. What happens if a user doesn't have access to the requested category?

2024-02-19 09:52 UTC, a-launois submitted a review, later dismissed

2024-02-19 09:52 UTC, a-launois commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +                            AND hc.level IS NOT NULL
⚠️ If you are in an on-prem platform with non-admin user, this request is to open, 
you have to filter hostgroups, host and hostcategories on the user's ACLs

I talked about it with @dmyios, you can see with him for more detailed explanations

2024-02-26 15:21 UTC, dmyios requested changes

2024-02-26 15:21 UTC, dmyios commented on centreon/doc/API/centreon-api-v24.04.yaml
> +        * host.category.id
```suggestion
        * hostcategory.id
        * hostcategory.name
```

2024-02-26 15:21 UTC, dmyios commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +        if (mb_strpos($requestParameters?->getSearchAsString() ?? '', 'host.category.id')) {
Unnecessary `if` statement, just append joins to your concatenator

2024-02-26 15:21 UTC, dmyios commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +            'host.category.name' => 'hc.hc_name',
```suggestion
            'hostcategory.id' => 'hc.hc_id',
            'hostcategory.name' => 'hc.hc_name',
```

2024-02-26 15:21 UTC, dmyios commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +                    SELECT DISTINCT
Why are you using `DISTINCT` here ?

2024-03-11 08:28 UTC, jeremyjaouen requested changes

2024-03-11 08:28 UTC, jeremyjaouen commented on centreon/src/Core/HostGroup/Infrastructure/Repository/DbReadHostGroupRepository.php
> +        );
like you did l.430 check for filter before doing the Join

2024-03-11 16:23 UTC, a-launois requested changes
I suggest that you check what Dmytro did on this two PRs:
https://github.com/centreon/centreon/pull/3351
https://github.com/centreon/centreon/pull/3407
The main attention points being the ACLs 
- on host (check if user has access to all hosts check) 
- as well as groups/categories (check if user has filtered access)

2024-03-14 08:27 UTC, closed without merging