enh(api) : add the posibility to search using host groups
centreon/centreon pull request #3275
Opened 2024-02-05 11:31 UTC by Exodiaaaa

## Description

Enhance endpoint GET: /configuration/hosts/groups by adding possibility to search by host categories

**Fixes** # (MON-34389)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [X] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

try to filter hostgroups using the new option on the filter : http://localhost:8080/centreon/api/v24.04/configuration/hosts/categories?search={"hostgroups_id":1}
You should create a hostgroups related to hostcategories to test it

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2024-02-07 09:09 UTC, jeremyjaouen requested changes

2024-02-07 09:09 UTC, jeremyjaouen commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +        if (! empty($_GET['search']) && mb_strpos($_GET['search'], 'host_group_id')) {
Do not use $_GET directly, the REquestParametersInterface has a method to do this check

https://github.com/centreon/centreon/blob/develop/centreon/src/Centreon/Domain/RequestParameters/Interfaces/RequestParametersInterface.php#L52

2024-02-13 08:08 UTC, tuntoja approved these changes
Approved GHA related changes.

2024-02-19 09:59 UTC, a-launois requested changes

2024-02-19 09:59 UTC, a-launois commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +                            ON hgr.hostgroup_hg_id = hg.hg_id
⚠️ If you are in an on-prem platform with non-admin user, this request is too open, 
you have to filter hostgroups, host and hostcategories on the user's ACLs

I talked about it with @dmyios, you can see with him for more detailed explanations

2024-02-21 09:39 UTC, a-launois requested changes

2024-02-21 09:39 UTC, a-launois commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +    }
Host group ACLs doesn't work on a "filter" system like the categories, but on the UI you can check a checkbox that gives you access to all host group. You need to check if this option with the hasAccessToAllHostGroups method

```suggestion
```

2024-02-21 09:39 UTC, a-launois commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +
```suggestion
            INNER JOIN `:db`.acl_groups ag
                ON argr.acl_group_id = ag.acl_group_id'
            LEFT JOIN `:db`.hostcategories_relation hcr
                ON hcr.host_host_id = host.host_id
            LEFT JOIN `:db`.host
                ON host.host_id = hsr.host_host_id
                AND host.host_register = '1'
            LEFT JOIN `:db`.hostgroup_relation hgr
                ON hgr.host_host_id = host.host_id
                {$hostGroupAcls}
            LEFT JOIN `:db`.hostgroup
                ON hostgroup.hg_id = hgr.hostgroup_hg_id
            SQL
        );
```

2024-02-26 08:02 UTC, kduret submitted a review, later dismissed
ok for CI changes

2024-02-26 14:53 UTC, dmyios requested changes

2024-02-26 14:53 UTC, dmyios commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +            'SELECT DISTINCT hc.hc_id, hc.hc_name, hc.hc_alias, hc.hc_activate, hc.hc_comment
No need for `DISTINCT` here

2024-02-26 14:53 UTC, dmyios commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +        if (mb_strpos($requestParameters?->getSearchAsString() ?? '' , 'host.group.id')) {
Innecessary `if` statement, just append joins to you concatenator

2024-02-26 14:53 UTC, dmyios commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +            <<< 'SQL'
```suggestion
            <<< SQL
```

2024-02-26 15:26 UTC, dmyios requested changes

2024-02-26 15:26 UTC, dmyios commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +                            ON hgr.hostgroup_hg_id = hg.hg_id
Use rather `LEFT JOIN`s

2024-02-26 15:26 UTC, dmyios commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +                        ON hostgroup.hg_id = hgr.hostgroup_hg_id
Use rather `LEFT JOIN`s

2024-03-11 08:27 UTC, jeremyjaouen commented on centreon/src/Core/HostCategory/Infrastructure/Repository/DbReadHostCategoryRepository.php
> +        $concatenator->appendJoins(
Like the other PR, check that the filter is present before doing the join

2024-03-11 16:22 UTC, a-launois reviewed
I suggest that you check what Dmytro has done on this two PRs:
https://github.com/centreon/centreon/pull/3351
https://github.com/centreon/centreon/pull/3407
The main attention points being the ACLs 
- on host (check if user has access to all hosts check) 
- as well as groups/categories (check if user has filtered access)

2024-03-11 16:24 UTC, a-launois requested changes
I suggest that you check what Dmytro did on this two PRs:
https://github.com/centreon/centreon/pull/3351
https://github.com/centreon/centreon/pull/3407
The main attention points being the ACLs

on host (check if user has access to all hosts check)
as well as groups/categories (check if user has filtered access)

2024-03-13 16:03 UTC, adr-mo commented
Closing this PR as I take back the subject. Thanks @Exodiaaaa for the help 💯

2024-03-13 16:03 UTC, closed without merging