enh(api) : add the posibility to search using host categories & host & host groups
centreon/centreon pull request #3315
Opened 2024-02-11 23:41 UTC by Exodiaaaa

## Description

Enhance endpoint GET: /configuration/services/groups by adding possibility to search by host categories

**Fixes** # (MON-34391)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [X] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

try to filter hostgroups using the new option on the filter : http://localhost:8080/centreon/api/v24.04/configuration/services/groups?search={"host_id":1} /{"host_group_id":1}/{"host_category_id":1}
You should create a hostcategorie to test it

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2024-02-12 10:14 UTC, adr-mo requested changes

2024-02-12 10:14 UTC, adr-mo commented on centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
> +        if (! empty($_GET['search']) && mb_strpos($_GET['search'], 'host_group_id')) {
@Exodiaaaa Hi,
⚠️ For repositories to handle the search request parameter we do not use the global GET variable ⚠️ 
Please see how it is done in this example https://github.com/centreon/centreon/blob/2d3e27f9e7c06cf57af268cbb7f82dc74f9c02bc/centreon/src/Core/Host/Infrastructure/Repository/DbReadHostRepository.php#L446

2024-02-14 13:47 UTC, paul-oureib submitted a review, later dismissed

2024-02-19 09:58 UTC, a-launois requested changes

2024-02-19 09:58 UTC, a-launois commented on centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
> +                    SQL
⚠️ This doesn't work
The servicegroups listed will be in the same ACLs Resource group as the host_group/host/host_category but it does'nt mean they are linked in terms of resource configuration
You need to join on the relation tables of servicegroup-service, service-host, host-hostgroup (for example)

But as in you other PRs on the same subject:
⚠️ If you are in an on-prem platform with non-admin user,
you have to filter hostgroups, host and hostcategories on the user's ACLs

I talked about it with @dmyios, you can see with him for more detailed explanations

2024-03-11 08:19 UTC, jeremyjaouen commented on centreon/src/Core/ServiceGroup/Infrastructure/Repository/DbReadServiceGroupRepository.php
> +            );
Like for the other PR, check that the filter is present before doing the Join

2024-03-11 16:21 UTC, a-launois requested changes
I suggest that you check what Dmytro did on this two PRs:
https://github.com/centreon/centreon/pull/3351
https://github.com/centreon/centreon/pull/3407
The main attention points being the ACLs 
- on host (check if user has access to all hosts check) 
- as well as groups/categories (check if user has filtered access)

2024-03-13 16:08 UTC, adr-mo commented
Closing this PR as I take back the subject. Thanks @Exodiaaaa for the help 💯

2024-03-13 16:08 UTC, closed without merging