enh(UI): Make fullscreen great again
centreon/centreon pull request #3418
Opened 2024-02-26 14:16 UTC by Thebarda

## Description

This re-add the fullscreen feature

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-02-26 14:52 UTC, cg-tw commented on centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
> +  it('enters in fullscreen mode when the button is clicked', () => {
```suggestion
  it('enters fullscreen mode when the button is clicked', () => {
```

2024-02-26 14:52 UTC, cg-tw commented on centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
> +  it('exits the fullscreen mode when the button is clicked', () => {
```suggestion
  it('exits fullscreen mode when the button is clicked', () => {
```

2024-02-26 14:52 UTC, cg-tw commented on centreon/packages/ui/src/utils/useFullscreen/Fullscreen.cypress.spec.tsx
> +  it('toggles the fullscreen mode when the corresponding shortcut is pressed', () => {
```suggestion
  it('toggles fullscreen mode when the corresponding shortcut is clicked', () => {
```

2024-02-26 14:52 UTC, cg-tw commented on centreon/packages/ui/src/utils/useFullscreen/translatedLabels.ts
> +export const labelCannotEnterInFullscreen = 'Cannot enter in fullscreen';
```suggestion
export const labelCannotEnterInFullscreen = 'Cannot enter fullscreen mode';
```

2024-02-26 14:52 UTC, cg-tw commented on centreon/www/front_src/src/Header/specs/Header.UserMenu.tsx
> +    it('enters in fullscreen mode when the corresponding icon is clicked', () => {
```suggestion
    it('enters fullscreen mode when the corresponding icon is clicked', () => {
```

2024-02-27 08:48 UTC, cg-tw submitted a review, later dismissed

2024-02-27 10:04 UTC, cg-tw approved these changes

2024-02-27 13:48 UTC, smau-centreon requested changes

2024-02-27 13:48 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Pas de données disponibles"
```suggestion
msgstr "Aucune donnée disponible"
```

2024-02-27 13:53 UTC, smau-centreon approved these changes

2024-02-27 14:07 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgid "No Data Available"
```suggestion
msgid "No data available"
```

2024-02-27 14:44 UTC, cg-tw approved these changes

2024-02-27 15:12 UTC, Noha-ElAbrouki approved these changes

2024-02-27 15:42 UTC, paul-oureib approved these changes

2024-02-27 15:55 UTC, merged