enh(UI): Use modal for delete actions on Dashboard
centreon/centreon pull request #3450
Opened 2024-02-27 19:58 UTC by Thebarda

## Description

This uses the modal on delete actions on Dashboard

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-02-28 14:43 UTC, smau-centreon requested changes

2024-02-28 14:43 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
>    it('sends a shares update request when the shares are update and the corresponding button is clicked', () => {
```suggestion
  it('sends a shares update request when the shares are updated and the corresponding button is clicked', () => {
```

2024-02-28 14:43 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
> +    it('does not displays the name of the widget a widget when the corresponding button is clicked', () => {
```suggestion
    it('does not display the name of the widget when the corresponding button is clicked', () => {
```

2024-02-28 14:43 UTC, smau-centreon commented on centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
> +  it('does not delete a dashboard in the listing when the corresponding icon button is clicked and the cancellation button is clicked', () => {
```suggestion
  it('does not delete a dashboard in the listing view when the corresponding icon button is clicked and the cancellation button is clicked', () => {
```

2024-02-28 15:07 UTC, paul-oureib approved these changes

2024-02-28 15:54 UTC, smau-centreon approved these changes

2024-02-29 07:46 UTC, Med1233 approved these changes

2024-02-29 08:55 UTC, paul-oureib approved these changes

2024-02-29 15:11 UTC, merged