enh(dashboards) : adapt the frontend to  status chart endpoint
centreon/centreon pull request #3613
Opened 2024-03-14 10:36 UTC by Med1233

## Description

adapt the frontend to  status chart endpoint

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x (master)

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-03-14 14:47 UTC, Thebarda approved these changes

2024-03-15 07:44 UTC, adr-mo requested changes

2024-03-15 07:44 UTC, adr-mo commented on centreon/www/install/insertBaseConf.sql
> +VALUES ('centreon-widget-statuschart');
```suggestion
INSERT INTO dashboard_widgets (`name`) VALUES
('centreon-widget-resourcestable'),
('centreon-widget-groupmonitoring'),
('centreon-widget-statuschart');
```

2024-03-15 07:45 UTC, Thebarda approved these changes

2024-03-15 07:45 UTC, adr-mo approved these changes

2024-03-15 08:12 UTC, merged