enh(dashboard) : update wording in some widgets
centreon/centreon pull request #4004
Opened 2024-05-03 04:45 UTC by Med1233

## Description

update wording in some widgets

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-05-06 07:18 UTC, Thebarda approved these changes

2024-05-06 09:25 UTC, smau-centreon requested changes

2024-05-06 09:25 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Afficher en"
```suggestion
msgstr "Afficher en tant que"
```

2024-05-06 09:28 UTC, smau-centreon approved these changes

2024-05-09 07:36 UTC, Thebarda approved these changes

2024-05-09 08:42 UTC, merged