Enh(UI): Display a message when the dashboard belongs to any playlist
centreon/centreon pull request #4027
Opened 2024-05-07 08:21 UTC by Thebarda

## Description

This displays a message when the dashboard belongs to any playlist.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevan.t details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-05-07 13:04 UTC, smau-centreon requested changes

2024-05-07 13:04 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Le tableau de bord {{name}} fait parti d'une ou plusieurs playlists. Il sera définitivement supprimé des playlists dont il appartient."
```suggestion
msgstr "Le tableau de bord {{name}} fait partie d'une ou plusieurs listes de diffusion. Il sera définitivement supprimé des listes de diffusion auxquelles il appartient."
```

2024-05-07 14:54 UTC, smau-centreon approved these changes

2024-05-09 08:53 UTC, Med1233 commented on centreon/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx
> +  it.only('deletes a dashboard in the listing view when the corresponding icon button is clicked and the confirmation button is clicked', () => {
```suggestion
  it('deletes a dashboard in the listing view when the corresponding icon button is clicked and the confirmation button is clicked', () => {
```

2024-05-09 13:38 UTC, Med1233 approved these changes

2024-05-15 10:14 UTC, smau-centreon approved these changes

2024-05-15 12:11 UTC, merged