doc(gorgone) add documentation for developper and pullwss connexion mode
centreon/centreon pull request #4113
Opened 2024-05-16 13:13 UTC by Evan-Adam

## Description
Add documentation for gorgone.

**Fixes** # MON-37896

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [X] 24.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-05-22 17:04 UTC, Evan-Adam commented on centreon-gorgone/docs/poller_pullwss_configuration.md
> +contrary to pull module, the communication is entierely done on http(s) websocket.
not done on all the rest of the gorgone doc.

2024-05-22 17:08 UTC, Evan-Adam commented on centreon-gorgone/docs/modules/core/proxy.md
>  #### Example
this is done in all gorgone doc.

2024-05-23 12:43 UTC, omercier requested changes

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules.md
> +Method called by event() when a ZMQ message is found.\
```suggestion
Method called by event() when a ZMQ message is found.

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/centreon/autodiscovery.md
> +The gorgone-action module does not send the result directly to the calling module. It sends a putlog message instead, processed by core.\
```suggestion
The gorgone-action module does not send the result directly to the calling module. It sends a putlog message instead, processed by core.

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/centreon/autodiscovery.md
> +![image](./centreon-gorgone-autodiscovery-archi.png)
```suggestion
![image](./centreon-gorgone-autodiscovery-archi.jpg)

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/centreon/autodiscovery.md
> +and dispatch another message to the waiting module.
```suggestion
Core keeps track of every module waiting for a particular event (use library.pm::addlistener to show interest in an event)
and dispatch another message to the waiting module.

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/core/proxy.md
> +this part of the configuration is only used if some poller must connect with pullwss module.
```suggestion
This part of the configuration is only used if some poller must connect with pullwss module.

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/core/proxy.md
> +| port          | tcp port to listen to.                                                                         |               |
```suggestion
| httpserver    | Array containing all below configuration for pullwss connnection                               | no value.     |
| enable        | Boolean if http server should be enabled                                                       | `false`       |
| ssl           | Should connection be made over tls/ssl or not                                                  | `false`       |
| ssl_cert_file | Path to a ssl certificate file. required if ssl: true                                          |               |
| ssl_key_file  | Path to a ssl key file associated to the certificate already configured. required if ssl: true |               |
| passphrase    | No idea, maybe an optionnal pasphrase for the ssl key.                                         |               |
| token         | Allow to authenticate node. It is required to enable the http server.                          |               |
| address       | Address to listen to. can be 0.0.0.0 to listen on all IPv4 address                             |               |
| port          | TCP port to listen to.                                                                         |               |

```

2024-05-23 12:43 UTC, omercier commented on centreon-gorgone/docs/modules/core/proxy.md
> +httpserver:  # this is used only if you want to configure pullwss nodes. to work you have to add register module and configure a config file.
```suggestion
httpserver:  # This is used only if you want to configure pullwss nodes. To make it work you have to add a *register module* file and set a configuration file.

```

2024-05-24 11:09 UTC, omercier submitted a review, later dismissed

2024-05-27 15:50 UTC, omercier submitted a review, later dismissed

2024-06-06 13:46 UTC, lpinsivy requested changes

2024-06-06 15:49 UTC, lpinsivy submitted a review, later dismissed

2024-06-12 13:01 UTC, cg-tw commented on centreon-gorgone/docs/modules.md
> +This class must inherit module.pm package.
```suggestion
This class must inherit the module.pm package.

```

2024-06-12 13:01 UTC, cg-tw commented on centreon-gorgone/docs/modules.md
> +This object is most of the time (maybe all ?) a singleton.
```suggestion
This object is most of the time a singleton (maybe every time).

```

2024-06-12 13:01 UTC, cg-tw commented on centreon-gorgone/docs/modules.md
> +(please keep the code base consistent if you make a new module).
```suggestion
(Please keep the code base consistent if you make a new module).

```

2024-06-12 13:24 UTC, Evan-Adam commented on centreon-gorgone/docs/modules/core/pullwss.md
> +Register will allow to keep the state of every poller, and find out the connexion mode.
Register module allow gorgone to keep the state, as this documentation is for futur developer, I think we don't need the 'you'

2024-06-12 13:43 UTC, Evan-Adam commented on centreon-gorgone/docs/modules/core/pullwss.md
> +Proxy have to bind to a tcp port for pullwss module to connect to.
```suggestion
Proxy module has to bind to a tcp port for pullwss module to connect to.
```

2024-06-12 13:53 UTC, Evan-Adam commented on centreon-gorgone/docs/modules/core/pullwss.md
> +Register will allow to keep the state of every poller, and find out the connexion mode.
```suggestion
Register Module will allow Gorgone to keep the state of every poller, and find out the connexion mode. 
```

2024-06-13 16:01 UTC, cg-tw commented on centreon-gorgone/docs/modules/core/pullwss.md
> +Proxy module has to bind to a tcp port for the pullwss module to connect to.
```suggestion
The proxy module has to bind to a tcp port for the pullwss module to connect to.
```

2024-06-13 16:01 UTC, cg-tw commented on centreon-gorgone/docs/modules/core/pullwss.md
> +Register Module will allow Gorgone to keep the state of every poller, and find out the connexion mode.
```suggestion
The register Module will allow Gorgone to keep the state of every poller, and find out the connexion mode. 
```

2024-06-24 09:40 UTC, Evan-Adam commented
@cg-tw  can you check this ?

2024-06-24 09:44 UTC, cg-tw approved these changes

2024-06-24 09:47 UTC, lucie-dubrunfaut approved these changes

2024-06-24 09:48 UTC, Evan-Adam commented
@coderabbitai pause

2024-06-24 09:50 UTC, merged