feat(NOTIFICATION): Unfrozen and take available time periods
centreon/centreon pull request #4306
Opened 2024-06-04 06:29 UTC by L0th0mat1c

## Description

- [SAAS-1319](https://centreon.atlassian.net/browse/SAAS-1379): Unfrozen and take available time periods

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [X] 24.04.x
- [X] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2024-06-06 13:30 UTC, a-launois requested changes

2024-06-06 13:30 UTC, a-launois commented on centreon/src/Core/Notification/Application/UseCase/AddNotification/AddNotification.php
> +            $newNotification = $notificationFactory->create($request->name, $request->isActivated, $request->timeperiodId);
You should check that timeperiod ID is valid (see ReadTimeperiodRepositoryInterface::exists())
you can add a new method for that in the NotificationValidator class (see example below)

Also, I would move the validator calls before the creation of the new Notification (just before the factory in fact) 

Example for a new method in the validator: 
```
    public function validateTimeperiod(int $timeperiodId): void
    {
        if (false === $this->readTimeperiodRepository->exists($timeperiodId)) {
            $this->error('Time period does not exist', ['timePeriodId' => $timeperiodId]);

            throw NotificationException::invalidId('timeperiod');
        }
    }
```

2024-06-20 14:19 UTC, Noha-ElAbrouki approved these changes

2024-07-26 07:50 UTC, mushroomempires approved these changes

2024-07-26 08:45 UTC, a-launois approved these changes

2024-07-26 10:23 UTC, Noha-ElAbrouki approved these changes

2024-07-29 16:26 UTC, merged