enh(UI): Enhance graph styles on Graph widget
centreon/centreon pull request #4322
Opened 2024-06-05 15:09 UTC by Thebarda

## Description

This adds a dozen of properties about graph styles for the graph widget.
(Video to come)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-06-10 09:14 UTC, smau-centreon requested changes

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Graph styles"
```suggestion
# msgid "Graph style"
```

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Graph styles"
```suggestion
# msgid "Graph style"
```

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Graph styles"
```suggestion
msgid "Graph style"
```

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Styles du graphe"
```suggestion
msgstr "Style du graphe"
```

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Graph styles"
```suggestion
# msgid "Graph style"
```

2024-06-10 09:14 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +# msgid "Graph styles"
```suggestion
# msgid "Graph style"
```

2024-06-10 10:01 UTC, smau-centreon approved these changes

2024-06-10 12:44 UTC, quborg commented on centreon/packages/ui/src/Graph/LineChart/Legend/LegendHeader.tsx
> +      className={cx(!isListMode ? classes.container : classes.containerList)}
pas besoin de cx()

2024-06-10 12:58 UTC, Noha-ElAbrouki submitted a review, later dismissed

2024-06-10 13:07 UTC, quborg submitted a review, later dismissed

2024-06-11 07:57 UTC, smau-centreon approved these changes

2024-06-11 09:47 UTC, Noha-ElAbrouki approved these changes

2024-06-11 12:38 UTC, Thebarda commented
@coderabbitai resolve all conversations

2024-06-11 12:42 UTC, merged