enh(install): improve vault steps style in wizard
centreon/centreon pull request #4410
Opened 2024-06-13 11:41 UTC by jeremyjaouen

## Description

This PR intends to add little improvement on the wizard:
- On Step6 the vault checkbox now appears dinamically depending of the activation of the vault feature flags
- Vault Step input have a increased width
- Correct a little typo saying that default path is root.

**Fixes** # MON-113489

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-06-13 13:00 UTC, a-launois approved these changes

2024-06-13 14:25 UTC, smau-centreon requested changes

2024-06-13 14:25 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Use vault to store sensitive data"
```suggestion
msgid "Use a vault to store sensitive data"
```

2024-06-13 14:58 UTC, wtermellil submitted a review, later dismissed

2024-06-14 07:18 UTC, smau-centreon approved these changes

2024-06-14 07:32 UTC, a-launois approved these changes

2024-06-14 07:49 UTC, wtermellil approved these changes

2024-06-14 09:01 UTC, merged