enh(conf/broker) Extend AddBrokerOutput into AddBrokerInputOutput to handle inputs
centreon/centreon pull request #4443
Opened 2024-06-19 13:36 UTC by a-launois

## Description

Modify AddBrokerOutput to handle inputs => AddBrokerInputOutput

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

2024-06-21 10:10 UTC, smau-centreon requested changes

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while updating a broker input/output"
```suggestion
#  msgid "Error while updating a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while adding a broker input/output"
```suggestion
#  msgid "Error while adding a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing input/output parameter: %s"
```suggestion
#  msgid "Missing the input/output parameter: %s"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d not found for broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while updating a broker input/output"
```suggestion
#  msgid "Error while updating a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error while adding a broker input/output"
```suggestion
msgid "Error while adding a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Missing input/output parameter: %s"
```suggestion
msgid "Missing the input/output parameter: %s"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Paramètre d'entrée/sortie manquant: %s"
```suggestion
msgstr "Ce paramètre d'entrée/sortie est manquant : %s"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Input/Output #%d not found for broker configuration #%d"
```suggestion
msgid "Input/Output #%d is not found for the Broker configuration #%d"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Entrée/Sortie #%d introuvable pour la configuration Broker #%d"
```suggestion
msgstr "L'entrée/sortie #%d est introuvable pour la configuration Broker #%d"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Error while updating a broker input/output"
```suggestion
msgid "Error while updating a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while adding a broker input/output"
```suggestion
#  msgid "Error while adding a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing input/output parameter: %s"
```suggestion
#  msgid "Missing the input/output parameter: %s"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d not found for broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while updating a broker input/output"
```suggestion
#  msgid "Error while updating a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while adding a broker input/output"
```suggestion
#  msgid "Error while adding a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing input/output parameter: %s"
```suggestion
#  msgid "Missing the input/output parameter: %s"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d not found for broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Error while updating a broker input/output"
```suggestion
#  msgid "Error while updating a Broker input/output"
```

2024-06-21 10:10 UTC, smau-centreon commented on centreon/src/Core/Broker/Infrastructure/API/AddBrokerInputOutput/AddBrokerInputOutputSchema.json
> +    "title": "Add an input or output to a broker configuration",
```suggestion
    "title": "Add an input or output to a Broker configuration",
```

2024-06-25 12:33 UTC, wtermellil submitted a review, later dismissed

2024-06-25 12:36 UTC, adr-mo submitted a review, later dismissed

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing the input/output parameter: %s"
```suggestion
#  msgid "Missing input/output parameter: %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d not found for Broker configuration #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing the input/output parameter: %s"
```suggestion
#  msgid "Missing input/output parameter: %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d not found for Broker configuration #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Missing the input/output parameter: %s"
```suggestion
msgid "Missing input/output parameter: %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Ce paramètre d'entrée/sortie est manquant : %s"
```suggestion
msgstr "Paramètre d'entrée/sortie manquant : %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Input/Output #%d is not found for the Broker configuration #%d"
```suggestion
msgid "Input/Output #%d not found for Broker configuration #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "L'entrée/sortie #%d est introuvable pour la configuration Broker #%d"
```suggestion
msgstr "Entrée/sortie #%d introuvable pour la configuration Broker #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing the input/output parameter: %s"
```suggestion
#  msgid "Missing input/output parameter: %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/pt_BR.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d not found for Broker configuration #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Missing the input/output parameter: %s"
```suggestion
#  msgid "Missing input/output parameter: %s"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +#  msgid "Input/Output #%d is not found for the Broker configuration #%d"
```suggestion
#  msgid "Input/Output #%d not found for Broker configuration #%d"
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/src/Core/Broker/Application/Exception/BrokerException.php
> +            sprintf(_('Missing the input/output parameter: %s'), $propertyName),
```suggestion
            sprintf(_('Missing input/output parameter: %s'), $propertyName),
```

2024-06-25 14:51 UTC, cg-tw commented on centreon/src/Core/Broker/Application/Exception/BrokerException.php
> +        return new self(sprintf(_('Input/Output #%d is not found for the Broker configuration #%d'), $outputId, $brokerId));
```suggestion
        return new self(sprintf(_('Input/Output #%d not found for Broker configuration #%d'), $outputId, $brokerId));
```

2024-06-25 14:52 UTC, cg-tw approved these changes

2024-06-25 14:55 UTC, adr-mo approved these changes

2024-06-25 14:55 UTC, wtermellil approved these changes

2024-06-25 16:01 UTC, merged