[WIP] feat(openid): store and retrieve client_id and client_secret into the vault
centreon/centreon pull request #4477
Opened 2024-06-25 08:37 UTC by jeremyjaouen

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-06-27 08:46 UTC, adr-mo approved these changes

2024-06-28 08:51 UTC, smau-centreon requested changes

2024-06-28 08:51 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "Unable to retrieve credentials ['%s'] from vault"
```suggestion
msgid "Unable to retrieve ['%s'] credentials from vault"
```

2024-06-28 08:51 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Impossible de récupérer les informations d'identification ['%s'] du coffre"
```suggestion
msgstr "Impossible de récupérer les informations d'identification de ['%s'] du coffre"
```

2024-06-28 08:57 UTC, smau-centreon approved these changes

2024-06-28 09:15 UTC, callapa approved these changes

2024-06-28 09:18 UTC, merged