Mon 139155
centreon/centreon pull request #4743
Opened 2024-07-25 12:14 UTC by adr-mo

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-07-25 14:13 UTC, adr-mo commented
@callapa @dmyios After our review two things were not changed:
- The exception will remain a generic one catched by the UseCase.
- The resourceId will remain null. If we do want to set it to a non nullable property this would require to pass it to the constructor and then modify the 83 occurrences found in the code for Resource entity (out of scope)

In the commit added regarding the documentation, I've changed the type of the 'extra' key to a simple object.

<img width="790" alt="image" src="https://github.com/user-attachments/assets/7fca8eeb-a4d7-4793-9956-3cc2b7471758">

2024-07-25 14:33 UTC, callapa submitted a review, later dismissed

2024-07-26 07:16 UTC, dmyios submitted a review, later dismissed

2024-07-29 14:59 UTC, a-launois requested changes

2024-07-29 18:05 UTC, adr-mo commented
@a-launois I can't use as phpcs-fixer keeps rename it to `resource`
Surely because Resource is a reserved word. I've changed it to ResourceEntity as it is done almost everywhere is Resource Status base code.

2024-07-30 07:08 UTC, jeremyjaouen approved these changes

2024-07-30 07:09 UTC, dmyios approved these changes

2024-07-31 08:24 UTC, a-launois approved these changes

2024-07-31 08:31 UTC, jdelpierre approved these changes
e2e part

2024-07-31 08:34 UTC, merged