feat(UI): Add widget clock/timer
centreon/centreon pull request #4811
Opened 2024-08-02 07:56 UTC by Thebarda

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-08-02 21:17 UTC, Thebarda commented on centreon/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
> +
@coderabbitai Stop providing translations

2024-08-02 21:18 UTC, Thebarda commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +
@coderabbitai Stop providing translations

2024-08-02 21:18 UTC, Thebarda commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +
@coderabbitai Stop providing translations

2024-08-02 21:18 UTC, Thebarda commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +
@coderabbitai Stop providing translations

2024-08-02 21:18 UTC, Thebarda commented on centreon/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
> +
@coderabbitai Stop providing translations

2024-08-12 08:30 UTC, smau-centreon requested changes

2024-08-12 08:30 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Sélectionner un format de temps"
```suggestion
msgstr "Sélectionner un format d'heure"
```

2024-08-12 08:30 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Fini à"
```suggestion
msgstr "Se termine à"
```

2024-08-12 08:30 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Format de temps"
```suggestion
msgstr "Format d'heure"
```

2024-08-20 12:48 UTC, MedWassCh approved these changes

2024-08-20 14:36 UTC, smau-centreon approved these changes

2024-08-21 07:39 UTC, dmyios approved these changes

2024-08-21 07:54 UTC, jeremyjaouen approved these changes

2024-08-21 08:03 UTC, L0th0mat1c approved these changes

2024-08-21 08:26 UTC, MedWassCh approved these changes

2024-08-21 08:27 UTC, smau-centreon approved these changes

2024-08-21 08:28 UTC, merged