chore(E2E): Implement backup e2e test
centreon/centreon pull request #4897
Opened 2024-08-22 13:28 UTC by MedWassCh

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-03 08:01 UTC, jdelpierre submitted a review, later dismissed

2024-09-04 08:21 UTC, mushroomempires requested changes

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    When the admin user acces to the backup page
```suggestion
    When the admin user accesses the backup page
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    Then backup is enable in UI
```suggestion
    Then the backup is enabled in the UI
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And backup directory is set
```suggestion
    And the backup directory is set
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And database backup options is set
```suggestion
    And the database backup options are set
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And Mysql configuration file path is set
```suggestion
    And the MySQL configuration file path is set
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    When the admin user acces to the backup page
```suggestion
    When the admin user accesses the backup page
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And the admin user selects full backup day
```suggestion
    And the admin user selects the "full backup day" option
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And the admin user saves the backup configuration and export the configuration
```suggestion
    And the admin user saves the backup configuration and exports the configuration
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    Then the database backups and configuration files should be present in the backup directory
```suggestion
    Then the database backups and configuration files are present in the backup directory
```

2024-09-04 08:21 UTC, mushroomempires commented on centreon/tests/e2e/features/Backup-configuration/01-backup-properties.feature
> +    And backup temporary is set
```suggestion
    And the backup temporary directory is set
```

this could probably be merged with the step right above

2024-09-04 14:56 UTC, mushroomempires approved these changes

2024-09-04 15:01 UTC, hamzabessa approved these changes

2024-09-04 15:55 UTC, merged