enh(CI): Improve linter report
centreon/centreon pull request #4914
Opened 2024-08-26 09:06 UTC by Thebarda

## Description

This improves the linter report on the CI.

![Screenshot 2024-08-26 at 10 54 32](https://github.com/user-attachments/assets/cf79b1be-b78d-48a0-86c4-e35b9ad3b05b)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-08-26 09:19 UTC, mushroomempires requested changes

2024-08-26 09:19 UTC, mushroomempires commented on .github/actions/frontend-lint/action.yml
> +    - uses: mongolyy/reviewdog-action-biome@v1
```suggestion
    - uses: mongolyy/reviewdog-action-biome@6b01155716493e5cc365df64aa0946ec9adc53c2 # v1.6.1
```

2024-08-27 06:40 UTC, kduret approved these changes

2024-08-27 10:24 UTC, mushroomempires approved these changes

2024-08-27 12:32 UTC, merged