fix(macros): Correctly set all host macros in on_demand_macro_host.infile
centreon/centreon pull request #4937
Opened 2024-08-28 07:56 UTC by jeremyjaouen

## Description

This PR intends to correctly set all host macros in on_demand_macro_host.infile

###Examples:
**Before:**
- Given an host monitored by a Remote Server with 3 macros  ["macro1" => "value1", "macro2" => "value2", "macro3" => "value3"]
- When exporting the configuration
- Then only 1 macro is write in the on_demand_macro_host.infile 
```
"14"~~~"$_HOSTMACRO1$"~~~"value1"~~~\N~~~\N
```

**After**
- Given an host monitored by a Remote Server with 3 macros  ["macro1" => "value1", "macro2" => "value2", "macro3" => "value3"]
- When exporting the configuration
- Then all macros is write in the on_demand_macro_host.infile 
```
"14"~~~"$_HOSTMACRO1$"~~~"value1"~~~\N~~~\N######"14"~~~"$_HOSTMACRO2$"~~~"value2"~~~\N~~~\N######"14"~~~"$_HOSTMACRO3$"~~~"value3"~~~\N~~~\N######
```

**Fixes** # MON-35503

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-08-29 08:02 UTC, a-launois approved these changes

2024-08-30 08:03 UTC, callapa requested changes

2024-08-30 09:17 UTC, jeremyjaouen commented on centreon/www/class/config-generate-remote/Relations/MacroHost.php
> +            );
Yes I discuss about it with AGR, we will update the pattern in CentreonLog to be compliant with centreon-web.log format

2024-08-30 12:17 UTC, callapa submitted a review, later dismissed

2024-09-03 15:24 UTC, callapa approved these changes

2024-09-04 13:32 UTC, a-launois approved these changes

2024-09-05 06:02 UTC, merged