feat(UI): Add vault configuration page
centreon/centreon pull request #5030
Opened 2024-09-06 07:45 UTC by Thebarda

## Description

This adds the new Vault configuration page.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-06 15:13 UTC, a-launois requested changes

2024-09-06 15:13 UTC, a-launois commented on centreon/www/install/php/Update-24.09.0.php
> +// Vault configuration
This should be in Update-24.10.0.php

2024-09-06 15:43 UTC, a-launois approved these changes

2024-09-12 13:55 UTC, a-launois approved these changes

2024-09-12 13:57 UTC, Noha-ElAbrouki submitted a review, later dismissed

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Identité du Role"
```suggestion
msgstr "Role ID"
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Identité du secret"
```suggestion
msgstr "Secret ID"
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Le port doit commencé à 1"
```suggestion
msgstr "Le numéro de port doit être au moins 1"
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "La configuration du Vaul a été mise à jour"
```suggestion
msgstr "La configuration du Vault a été mise à jour"
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Script à exécuter en tant que root sur le central."
```suggestion
msgstr "Exécuter ce script en tant que root sur le serveur central."
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Le script suivant migrera vos identifiances de Centreon, Auto-discovery ainsi que de la base de données."
```suggestion
msgstr "Le script suivant migrera vos identifiants de Centreon, d'Auto-discovery ainsi que de la base de données."
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "By executing this script, your platform will be in a locked mode and you not be able to do <strong>anything</strong> during the migration process (example: exporting your configuration, updati
```suggestion
msgid "By executing this script, your platform will be in a locked mode and you will not be able to do <strong>anything</strong> during the migration process (example: exporting your configuration, updating administration parameters, etc...)."
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "En exécutant ce script, votre plateforme entrera sera vérouillé and vous ne pourrez plus <strong>rien modifier</strong> durant le processus de migration (exemple: exporter la configuration, m
```suggestion
msgstr "En exécutant ce script, votre plateforme sera verrouillée and vous ne pourrez plus <strong>rien modifier</strong> durant le processus de migration (exemple: déployer la configuration, modifier les paramètres d'administration, etc...)."
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx
> +  it('sanitizes URL and port field when URL field receives an URL and a port', () => {
```suggestion
  it('sanitizes the URL field when it receives a URL and a port', () => {
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/www/front_src/src/VaultConfiguration/VaultConfiguration.cypress.spec.tsx
> +      'By executing this script, your platform will be in a locked mode and you not be able to do'
```suggestion
      'By executing this script, your platform will be in a locked mode and you will not be able to do'
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/www/front_src/src/VaultConfiguration/translatedLabels.ts
> +export const labelPortMustStartFrom1 = 'Port must start from 1';
```suggestion
export const labelPortMustStartFrom1 = 'Port number must be at least 1';
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/www/front_src/src/VaultConfiguration/translatedLabels.ts
> +export const labelPortExpectedAtMost = 'Port expected at most 65535';
```suggestion
export const labelPortExpectedAtMost = 'Port number must be at most 65535';
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/www/front_src/src/VaultConfiguration/translatedLabels.ts
> +  'By executing this script, your platform will be in a locked mode and you not be able to do <strong>anything</strong> during the migration process (example: exporting your configuration, updating a
```suggestion
  'By executing this script, your platform will be in a locked mode and you will not be able to do <strong>anything</strong> during the migration process (example: deploying your configuration, updating administration parameters, etc...).';
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Le port maximum attendu est 65535"
```suggestion
msgstr "Le numéro de port maximum attendu est 65535"
```

2024-09-12 14:58 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgid "By executing this script, your platform will be in a locked mode and you not be able to do <strong>anything</strong> during the migration process (example: exporting your configuration, updati
```suggestion
msgid "By executing this script, your platform will be in a locked mode and you not be able to do <strong>anything</strong> during the migration process (example: deploying your configuration, updating administration parameters, etc...)."
```

2024-09-12 15:11 UTC, cg-tw submitted a review, later dismissed

2024-09-12 15:48 UTC, a-launois submitted a review, later dismissed

2024-09-13 07:16 UTC, cg-tw submitted a review, later dismissed

2024-09-13 07:51 UTC, a-launois submitted a review, later dismissed

2024-09-13 08:06 UTC, Noha-ElAbrouki submitted a review, later dismissed

2024-09-13 12:33 UTC, jeremyjaouen requested changes

2024-09-13 12:33 UTC, jeremyjaouen commented on centreon/www/front_src/src/VaultConfiguration/Form/MigrationModal.tsx
> +          commandToCopy="/usr/share/centreon/bin/migrateCredentials.php"
```suggestion
          commandToCopy="php /usr/share/centreon/bin/migrateCredentials.php"
```

2024-09-13 14:18 UTC, jeremyjaouen approved these changes

2024-09-13 14:21 UTC, cg-tw approved these changes

2024-09-13 15:52 UTC, Noha-ElAbrouki approved these changes

2024-09-13 15:53 UTC, Med1233 approved these changes

2024-09-13 16:36 UTC, merged