enh(dashboads): front enhancements for the open ticket wigets
centreon/centreon pull request #5033
Opened 2024-09-08 20:29 UTC by Med1233

## Description

- enhance “opened on” date formatting

- when opening a ticket, modal should be bigger

- replace “open ticket” wording by “ticket”

- case wording fix: standardize “Hide services…” and “hide services…”

- widget props: collapse open tickets props

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-09 07:34 UTC, Thebarda approved these changes

2024-09-09 13:35 UTC, jeremyjaouen submitted a review, later dismissed

2024-09-10 11:28 UTC, Med1233 commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
>  msgstr "Activer Open Tickets"
```suggestion
msgstr "Activer les tickets"
```

2024-09-10 11:30 UTC, Med1233 commented on centreon/www/widgets/src/centreon-widget-resourcestable/src/Listing/translatedLabels.ts
> +export const labelTicket = 'Ticket';
```suggestion
export const labelTicket = 'Tickets';
```

2024-09-24 08:07 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Autocomplete/ConnectedAutocomplete.tsx
> +          required= {isRequiredProperty}
```suggestion
          required={isRequiredProperty}
```

2024-09-24 08:07 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Autocomplete/ConnectedAutocomplete.tsx
> +          required= {isRequiredProperty}
```suggestion
          required={isRequiredProperty}
```

2024-09-24 08:07 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.cypress.spec.tsx
> +    cy.contains(label);
```suggestion
    cy.contains(label).should('be.visible');
```

2024-09-24 08:07 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Warning.cypress.spec.tsx
> +    initialize({label });
```suggestion
    initialize({ label });
```

2024-09-24 08:07 UTC, Thebarda commented on centreon/www/widgets/src/centreon-widget-resourcestable/src/spec/ResourcesTable.cypress.spec.tsx
> +    cy.contains('Ticket');
```suggestion
    cy.contains('Ticket').should('be.visible');
```

2024-09-25 07:07 UTC, tuntoja approved these changes
approved feature.json

2024-09-25 11:27 UTC, cg-tw approved these changes

2024-09-25 11:39 UTC, jeremyjaouen commented on centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/closeTicket/action.php
> +$data = isset($payload['data']) ? $payload['data'] : null;
```suggestion
$data = $payload['data'] ?? null;
```

2024-09-25 11:47 UTC, Thebarda approved these changes

2024-09-25 11:55 UTC, cg-tw submitted a review, later dismissed

2024-09-25 11:56 UTC, jeremyjaouen approved these changes
LGTM For PHP

2024-09-25 12:25 UTC, Drago37 requested changes

2024-09-25 12:25 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/closeTicket/action.php
> +    || ! is_int((int) $data['rule_id'])
Hummm strange, use is_int() and the cas in same time is very strange :) you will have a integer all the time ;) You can remove the cast ;)

2024-09-25 12:49 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/views/rules/closeTicket/action.php
> +    || ! is_int((int) $data['rule_id'])
ok

2024-09-25 12:49 UTC, Drago37 approved these changes

2024-09-25 13:26 UTC, MedWassCh approved these changes

2024-09-25 13:28 UTC, quborg approved these changes

2024-09-25 13:32 UTC, cg-tw approved these changes

2024-09-25 14:31 UTC, tuntoja approved these changes
approved features.json changes

2024-09-25 14:31 UTC, merged