fix (open-ticket): fix sql request
centreon/centreon pull request #5048
Opened 2024-09-10 14:43 UTC by selfakiri

## Description

Fix sql request in open-ticket

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-12 07:31 UTC, Drago37 requested changes

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            while (($row = $graphStatement->fetch())) {
Now, it's recommended to use CentreonDb::fetch() :)

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            while (($row = $hostServiceStatement->fetch())) {
Now, it's recommended to use CentreonDb::fetch() :)

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            $dbStorage->executePreparedQuery($hostServiceStatement, $queryParams);
How to manage the CentreonDbException ?

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            $dbStorage->executePreparedQuery($graphStatement, $queryParams);
How to manage the CentreonDbException ?

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            $dbStorage->executePreparedQuery($hostStatement, $queryParams);
How to manage the CentreonDbException ?

2024-09-12 07:31 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +            while (($row = $hostStatement->fetch())) {
Now, it's recommended to use CentreonDb::fetch() :)

2024-09-12 07:32 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +    public function loadSelection(?CentreonDB $dbStorage, string $cmd, string $selection): array
The typing of $cmd and $selection is ricky because sometimes this method is called with arguments that have not been checked before. No ?

2024-09-17 07:50 UTC, Drago37 commented on centreon-open-tickets/www/modules/centreon-open-tickets/class/rule.php
> +    public function loadSelection(?CentreonDB $dbStorage, string $cmd, string $selection): array
Seen together it's ok

2024-09-17 07:51 UTC, Drago37 approved these changes

2024-09-17 07:56 UTC, dmyios approved these changes

2024-09-17 09:00 UTC, merged