chore(php): migrate to php 8.2
centreon/centreon pull request #5098
Opened 2024-09-13 10:04 UTC by kduret

## Description

chore(php): migrate to php 8.2

**Fixes** MON-146850

2024-09-30 09:16 UTC, tuntoja requested changes
wait for 24.10 bump before merging

2024-10-03 06:54 UTC, tuntoja approved these changes

2024-10-03 09:34 UTC, MedWassCh approved these changes

2024-10-03 15:25 UTC, Drago37 approved these changes

2024-10-03 15:39 UTC, Thebarda approved these changes

2024-10-03 15:40 UTC, cg-tw approved these changes

2024-10-04 06:47 UTC, merged