Disable Service Checks When Host Down option in Engine configuration …
centreon/centreon pull request #5175
Opened 2024-09-25 08:34 UTC by dmyios

…of Pollers added

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-26 15:30 UTC, callapa requested changes

2024-09-26 15:30 UTC, callapa commented on centreon/www/include/configuration/configServers/DB-Func.php
> +    $results = $pearDB->executeQuery($query);
Please use a prepare request.

2024-09-26 15:30 UTC, callapa commented on centreon/www/install/php/Update-24.10.0.php
> +                ADD COLUMN `host_down_disable_service_checks` ENUM('0', '1') DEFAULT '0'
```suggestion
                ADD COLUMN `host_down_disable_service_checks` ENUM('0', '1') DEFAULT NULL
```

2024-09-27 08:05 UTC, dmyios commented on centreon/www/install/php/Update-24.10.0.php
> +                ADD COLUMN `host_down_disable_service_checks` ENUM('0', '1') DEFAULT '0'
corrected in installation script

2024-09-27 08:06 UTC, dmyios commented on centreon/www/include/configuration/configServers/DB-Func.php
> +    $results = $pearDB->executeQuery($query);
Done

2024-09-27 08:25 UTC, a-launois submitted a review, later dismissed

2024-09-27 09:22 UTC, dmyios commented on centreon/www/include/configuration/configServers/DB-Func.php
> +    $separator = $pearDB->escapeString($separator);
```suggestion
```

2024-09-27 11:37 UTC, callapa approved these changes

2024-09-27 12:03 UTC, a-launois approved these changes

2024-09-27 12:04 UTC, merged