fix(configuration): remove deprecated macros & add new ones
centreon/centreon pull request #5187
Opened 2024-09-26 13:20 UTC by selfakiri

## Description

Configuration : Remove deprecated macros & add new ones

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-09-30 08:33 UTC, adr-mo requested changes
Hi @selfakiri you have handled **the fresh installation of Centreon** but you are missing the upgrade.
On upgrade to the next minor / major version nothing will be changed without an upgrade script

2024-09-30 08:42 UTC, selfakiri commented
> Hi @selfakiri you have handled **the fresh installation of Centreon** but you are missing the upgrade. On upgrade to the next minor / major version nothing will be changed without an upgrade script

Hello @adr-mo, I have a few questions regarding the upgrade process:
1. Should I handle the upgrade in this PR or in the backports?
2. Regarding update scripts, should I:
a) Add scripts for all minor versions (from zero to nine), or
b) Create one script per major version (only for 203.10.0 and 24.04.0)?

2024-10-02 08:33 UTC, callapa requested changes

2024-10-02 08:33 UTC, callapa commented on centreon/www/install/php/Update-24.09.0.php
> +$updateNagiosMacros =  function (CentreonDB $pearDB) use (&$errorMessage): void {
Your script must be idempotent.

2024-10-03 13:53 UTC, callapa commented on centreon/www/install/php/Update-24.10.1.php
> +            INSERT IGNORE INTO `nagios_macro` (`macro_name`)
```suggestion
            INSERT INTO `nagios_macro` (`macro_name`)
```

2024-10-03 13:55 UTC, callapa approved these changes

2024-10-04 08:29 UTC, adr-mo approved these changes

2024-10-04 12:56 UTC, merged