enh(ceip): add agent configuration to ceip stats
centreon/centreon pull request #5237
Opened 2024-10-03 14:56 UTC by a-launois

## Description
Add  poller/agent configuration stat to CEIP cron:
- total of configurations
- total of configurations per type
- total of pollers per type
```
{
    ...
    "poller-agent-configuration": {
        "total": int,
        "telegraf": { 
            "configuration": int, 
            "pollers": int
        },
       ...
    }
}
```

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

2024-10-25 07:55 UTC, Drago37 requested changes

2024-10-25 07:55 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        $total = $statement->fetchColumn();
Now, with CentreonDB, you must not to use PDO native, but the metods of CentreonDB ;) 
```suggestion
        $total = $this->dbConfig->fetchColumn($statement);
```

2024-10-25 07:55 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        }
Now, with CentreonDB, you must not to use PDO native, but the metods of CentreonDB ;) 
Also, a variable to store the result of fetchAll before the loop is more optimized :)
```suggestion
        $acAndPollerPerType = $this->dbConfig->fetchAll($statement);
        foreach ($acAndPollerPerType as $row) {
            $data[$row['type']]['configuration'] = $row['nb_ac_per_type'];
            $data[$row['type']]['pollers'] = $row['nb_poller_per_type'];
        }
```

2024-10-25 07:55 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        $statement = $this->dbConfig->executeQuery(
Please note that the method doesn't have the @throw tag in her php docs to alert she can throw a CentreonDbException ;)

2024-11-04 07:18 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        $statement = $this->dbConfig->executeQuery(
good !

2024-11-04 07:19 UTC, Drago37 approved these changes

2024-11-04 07:20 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        $total = $statement->fetchColumn();
ok

2024-11-04 07:20 UTC, Drago37 commented on centreon/www/class/centreonStatistics.class.php
> +        }
ok

2024-11-05 11:14 UTC, jeremyjaouen approved these changes

2024-11-05 11:14 UTC, merged