[E2E] Rewrite HostConfiguration.feature
centreon/centreon pull request #5243
Opened 2024-10-03 16:18 UTC by s-elhassani

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-10-04 08:38 UTC, mushroomempires requested changes

2024-10-04 08:38 UTC, mushroomempires commented on centreon/tests/e2e/features/Hosts/01-host-configuration.feature
i'd say you should rewrite the tests using third-person perspective instead of first-person perspective to follow the standards set by the rest of the gherkin files

2024-10-08 12:40 UTC, MedWassCh approved these changes

2024-10-08 13:01 UTC, mushroomempires approved these changes

2024-10-08 13:45 UTC, callapa approved these changes

2024-10-09 08:46 UTC, merged