fix : dead code removed or possible bugs fixed post migration php 8.2
centreon/centreon pull request #5265
Opened 2024-10-04 13:08 UTC by Drago37

## Description

### Fixed

* dead code removed or possible bugs fixed post migration php 8.2

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] develop

<h2> How this pull request can be tested ? </h2>

Check source code with debug if need.

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-10-08 09:06 UTC, a-launois requested changes

2024-10-08 09:06 UTC, a-launois commented on centreon/www/class/centreonUser.class.php
> +     * @return void
There is a return null L489

2024-10-14 07:12 UTC, Drago37 commented on centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
> +        }
I saw it with @callapa to exit on error, @callapa can you confirm it's ok please ? Thanks.
Also, I fix the pollerRestart method 😄

2024-10-14 07:20 UTC, Drago37 commented on centreon/www/class/centreonConnector.class.php
> -    /**
arf no I am not sure so I have been a rollback of this deleted method and I have fixed a bug with a variable not initialized. Can you see if it's ok please ?

2024-10-14 07:21 UTC, Drago37 commented on centreon/www/class/centreonTraps.class.php
>       */
php docs fixed thanks !

2024-10-14 07:22 UTC, Drago37 commented on centreon/www/class/centreonUser.class.php
> +     * @return void
php docs fixed

2024-10-14 07:26 UTC, Drago37 commented on centreon/www/class/centreonUser.class.php
> -    public $groupListStr; //FIXME not in this class
A hab done a rollback to add the deleted properties. Thanks

2024-10-17 10:12 UTC, a-launois commented on centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
> +        // centreon -u admin -p Centreon\!2021 -a POLLERRELOAD -v 1
```suggestion
```

2024-10-17 11:42 UTC, Drago37 commented on centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
> +        }
fixed

2024-10-17 11:42 UTC, Drago37 commented on centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php
> +        // centreon -u admin -p Centreon\!2021 -a POLLERRELOAD -v 1
fixed

2024-10-18 08:20 UTC, a-launois approved these changes

2024-10-21 09:25 UTC, merged