feat(dashboards): Add management of favorite dashboards
centreon/centreon pull request #5384
Opened 2024-10-15 20:32 UTC by Med1233

## Description

The goal is to offer users a way to mark their favorite dashboards so they can easily retrieve them.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-10-16 07:54 UTC, Thebarda commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards --  creator role Dashboard favorite -- View as cards toggles the dashboard favorite status when the favorite button is clicked.snap.png
As the favorite icon is always visible no matter the user ACL, can we agree to display it in the same place either at the bottom left, bottom right or top left of the card ? What do you think @Wedierre and @Med1233

2024-10-16 07:54 UTC, Thebarda commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards --  creator role Dashboard favorite -- View as cards toggles the dashboard favorite status when the favorite button is clicked.snap.png
As the favorite icon is always visible no matter the user ACL, can we agree to display it in the same place either at the bottom left, bottom right or top left of the card ? What do you think @Wedierre and @Med1233

2024-10-16 07:54 UTC, Thebarda commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/Dashboards/Dashboards.cypress.spec.tsx/Dashboards --  creator role Dashboard favorite -- View as list displays the favorite icons in the correct state.snap.png
Same comment here, the favorite should remain at the same position (the first position)

2024-10-16 07:54 UTC, Thebarda commented on centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
> +  fovoriteAction?: JSX.Element;
```suggestion
```

2024-10-16 07:54 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.cypress.spec.tsx
> +import { profileEndpoint } from 'www/front_src/src/api/endpoint';
use relative import

2024-10-16 07:54 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
> +            { !isOnPublicPage && <Favorite dashboardId = {Number(dashboardId)} isFavorite = {isFavorite} />}
```suggestion
            { !isOnPublicPage && <Favorite dashboardId={Number(dashboardId)} isFavorite={isFavorite} />}
```

2024-10-16 07:54 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Dashboard.tsx
> +    [profile]
```suggestion
    [profile, dashboardId]
```

2024-10-16 07:54 UTC, Thebarda commented on centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
> +      fovoriteAction
```suggestion
```
Why did you create a prop for favorite actions as the Favorite icon is already in the Actions prop

2024-10-16 07:54 UTC, Thebarda commented on centreon/packages/ui/src/components/DataTable/Item/DataTableItem.tsx
> +            <span>{hasActions ? Actions : fovoriteAction}</span>
```suggestion
            <span>{Actions}</span>
```

2024-10-16 07:54 UTC, Thebarda commented on centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardsOverview/DashboardsOverview.tsx
> +          }
```suggestion
```

2024-10-16 18:34 UTC, Thebarda approved these changes

2024-10-17 09:21 UTC, quborg approved these changes

2024-10-17 09:23 UTC, quborg approved these changes

2024-10-18 12:22 UTC, smau-centreon requested changes

2024-10-18 12:22 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Tableau de bord désélectionné comme favori"
```suggestion
msgstr "Tableau de bord non marqué comme favori"
```

2024-10-18 12:22 UTC, smau-centreon commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Désélectionner comme favori"
```suggestion
msgstr "Ne plus marquer comme favori"
```

2024-10-18 14:39 UTC, merged