enh(Change Logs): insert log changes into ServiceTemplate actions
centreon/centreon pull request #5450
Opened 2024-10-22 07:53 UTC by asalhi-ext

add  log changes into ServiceTemplate actions

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

<h2> How this pull request can be tested ? </h2>

check [ticket](https://centreon.atlassian.net/browse/MON-107633)

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-10-22 08:00 UTC, dmyios requested changes

2024-10-22 08:39 UTC, asalhi-ext commented on centreon/src/Core/ServiceTemplate/Application/Repository/DbWriteServiceTemplateActionLogRepository.php
> +
resolved

2024-10-22 08:43 UTC, dmyios submitted a review, later dismissed

2024-10-25 07:31 UTC, a-launois submitted a review, later dismissed

2024-10-28 06:54 UTC, asalhi-ext commented on centreon/src/Core/ServiceTemplate/Infrastructure/Repository/DbWriteServiceTemplateActionLogRepository.php
> +    }
doesn't need it

2024-10-28 09:28 UTC, a-launois approved these changes

2024-10-29 08:08 UTC, merged