fix(widgets): fix query for Live Top 10 Memory usage
centreon/centreon pull request #5532
Opened 2024-10-28 15:06 UTC by selfakiri

## Description

Fix(widgets): fix query for Live Top 10 Memory usage

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 22.10.x
- [x] 23.04.x
- [x] 23.10.x
- [x] 24.04.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-10-29 08:16 UTC, Drago37 requested changes

2024-10-29 08:16 UTC, Drago37 commented on centreon/www/widgets/live-top10-memory-usage/index.php
> +$statement->execute();
* You must to use the new methods of CentreonDB to replace the old methods ;)
* you can catch CentreonDbException to add a business log with CentreonLog :)
* bindValue() is useless except for the limit ;)

2024-10-30 09:08 UTC, Drago37 commented on centreon/www/widgets/live-top10-memory-usage/index.php
> +$statement->execute();
top ! thanks for your changes :)

2024-10-30 09:08 UTC, Drago37 approved these changes

2024-11-04 08:10 UTC, adr-mo approved these changes

2024-11-04 08:12 UTC, merged