enh(conf): use timeperiod endpoints in UI conf forms (create/update/delete)
centreon/centreon pull request #5562
Opened 2024-10-30 10:43 UTC by a-launois

## Description

Call endpoints in legacy code for create/update/delete action in UI timeperiod forms

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [x] master

2024-11-04 08:20 UTC, Drago37 requested changes

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        return $timeperiodId;
```suggestion
        return insertTimeperiodByApi($formData, $basePath);
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @throws Exception
There is several exceptions that are not in the php docs, you can use this suggestion to fix the alert
```suggestion
 * @throws Throwable
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
here you need to write a log with new methods of centreonLog to log the error to improve error handling ;) 
```suggestion
    } catch (Throwable $th) {
        CentreonLog::create()->error(
            logTypeId: CentreonLog::TYPE_BUSINESS_LOG,
            message: "Error while inserting timeperiod by api : {$th->getMessage()}",
            customContext: ['form_data' => $formData, 'base_path' => $basePath],
            exception: $th
        );
        
        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
here you need to write a log with new methods of centreonLog to log the error to improve error handling ;) 
```suggestion
    } catch (Throwable $th) {
        CentreonLog::create()->error(
            logTypeId: CentreonLog::TYPE_BUSINESS_LOG,
            message: "Error while updating timeperiod by api : {$th->getMessage()}",
            customContext: ['form_data' => $formData, 'base_path' => $basePath],
            exception: $th
        );
        
        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @throws Exception
There is several exceptions that are not in the php docs, you can use this suggestion to fix the alert
```suggestion
 * @throws Throwable
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +            'body' => json_encode($payload),
json_encode can return false on failure, you can use [JSON_THROW_ON_ERROR] (https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error) flag to improve error handling ;)

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        $content = json_decode($response->getContent(false));
json_decode can return null on failure, you can use [JSON_THROW_ON_ERROR] (https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error) flag to improve error handling ;)

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
```suggestion
    } catch (Throwable $th) {
        CentreonLog::create()->error(
            logTypeId: CentreonLog::TYPE_BUSINESS_LOG,
            message: "Error while deleting timeperiod by api : {$th->getMessage()}",
            customContext: ['timeperiods' => $timeperiods, 'base_path' => $basePath],
            exception: $th
        );
        
        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> + * @throws Exception
There is several exceptions that are not in the php docs, you can use this suggestion to fix the alert
```suggestion
 * @throws Throwable
```

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +            $content = json_decode($response->getContent(false));
json_decode can return null on failure, you can use [JSON_THROW_ON_ERROR] (https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error) flag to improve error handling ;)

2024-11-04 08:20 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        'alias' => $formData['tp_alias'],
Are you sure that these variables are isset all the time :) ?

2024-11-14 08:40 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
Are you sure you want to send the exception  message back to the user ? It is not often user-friendly :)

2024-11-14 08:47 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        $content = json_decode($response->getContent(false));
Don't forget it please :)

2024-11-14 08:48 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        'alias' => $formData['tp_alias'],
Ok for me !

2024-11-15 12:29 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        $content = json_decode($response->getContent(false));
ok for me :)

2024-11-15 12:29 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        $content = json_decode($response->getContent(false));
ok for me :)

2024-11-15 12:29 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +            $content = json_decode($response->getContent(false));
ok for me :)

2024-11-15 12:30 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
seen together it's ok

2024-11-15 12:30 UTC, Drago37 commented on centreon/www/include/configuration/configObject/timeperiod/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _($th->getMessage()) . '</div>';
seen together it's ok

2024-11-15 12:30 UTC, Drago37 submitted a review, later dismissed

2024-11-21 08:14 UTC, callapa approved these changes

2024-11-27 07:07 UTC, Drago37 approved these changes

2024-11-27 08:38 UTC, callapa approved these changes

2024-11-27 08:39 UTC, merged