enh(map): 24.04 - Change window size lime in cypress config
centreon/centreon pull request #5591
Opened 2024-11-04 11:54 UTC by Yassir-BenBOUBKER

2024-11-04 12:00 UTC, Med1233 approved these changes

2024-11-04 12:52 UTC, Thebarda approved these changes

2024-11-05 08:09 UTC, quborg submitted a review, later dismissed

2024-11-05 08:44 UTC, Thebarda requested changes

2024-11-05 08:44 UTC, Thebarda commented on centreon/packages/js-config/cypress/component/configuration.js
> +            launchOptions.args.push('--window-size=1400,1200');
It breaks snapshots sizes https://github.com/centreon/centreon/actions/runs/11680375631/job/32523274073

2024-12-12 15:58 UTC, Thebarda approved these changes

2024-12-12 16:03 UTC, Noha-ElAbrouki approved these changes

2024-12-13 10:06 UTC, merged