enh(ACC):  translation and ux enhancements
centreon/centreon pull request #5765
Opened 2024-11-19 15:22 UTC by Med1233

## Description

**PLEASE MAKE SURE THAT THE BRANCH PR INCLUDES JIRA TICKET ID** (_for centreon-internal_)

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [ ] master

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-11-19 16:23 UTC, Thebarda approved these changes

2024-11-21 08:33 UTC, quborg approved these changes

2024-11-21 09:33 UTC, dmyios submitted a review, later dismissed

2024-11-21 09:56 UTC, a-launois requested changes

2024-11-21 09:56 UTC, a-launois commented on centreon/www/install/php/Update-24.10.3.php
> +
```suggestion
```

2024-11-21 09:56 UTC, a-launois commented on centreon/www/install/php/Update-24.10.3.php
> +    $pearDB->executePreparedQuery($constraintStatement, [':show' => $isCentral === 'yes' ? '1' : '0']);
```suggestion
    $pearDB->executePreparedQuery($constraintStatement);
```

2024-11-21 09:56 UTC, a-launois commented on centreon/www/install/php/Update-24.10.3.php
> +    $addDisableServiceCheckColumn($pearDB);
```suggestion
```

2024-11-21 09:58 UTC, a-launois requested changes

2024-11-21 09:58 UTC, a-launois commented on centreon/www/install/php/Update-24.10.3.php
> +    $constraintStatement = $pearDB->prepareQuery(
```suggestion
    $constraintStatement = $pearDB->executeQuery(
```

2024-11-21 10:08 UTC, Thebarda commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
The scroll in host configurations disappeared so you cannot scroll within host configurations

2024-11-21 10:09 UTC, Thebarda commented
And changes are made on AC page, not on ACC

2024-11-21 10:17 UTC, Med1233 commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
oops

2024-11-21 10:21 UTC, Med1233 commented
> And changes are made on AC page, not on ACC

In fact, on both pages

2024-11-21 10:27 UTC, Med1233 commented on centreon/www/install/php/Update-24.10.3.php
> +    );
```suggestion
    );
    $isCentral = $statement->fetch(PDO::FETCH_COLUMN);
```

2024-11-21 10:29 UTC, Med1233 commented on centreon/www/install/php/Update-24.10.3.php
> +    );
```suggestion
    );
    $pearDB->executePreparedQuery($constraintStatement);
```

2024-11-21 10:38 UTC, Med1233 commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
I just checked that the cursor does exist, but it's not visible

2024-11-21 10:38 UTC, Med1233 commented on centreon/cypress/visual-testing-snapshots/www/front_src/src/AgentConfiguration/AgentConfigurations.cypress.spec.tsx/Agent configurations modal -- adds a new host configuration when the corresponding button is clicked.snap.png
I suppose it's related to the OS

2024-11-21 11:01 UTC, dmyios approved these changes

2024-11-21 13:09 UTC, a-launois commented on centreon/www/install/php/Update-24.10.3.php
> +    $pearDB->executePreparedQuery($constraintStatement);
```suggestion
```

2024-11-21 14:15 UTC, merged