enh(ci): Add rpm delivery cleanup and structure
centreon/centreon pull request #577
Opened 2022-12-26 08:11 UTC by tuntoja

## Description

Add rpm delivery repository cleanup after delivery to avoid having too many rpms and slowdown of repository browsing
Add rpm unstable and testing repository structure to properly match the old structure and allow cleanup

**Fixes** # (issue)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-12-26 10:03 UTC, kduret commented on .github/actions/rpm-delivery/action.yml
> +          #FOLDER=$(basename $FILE .rpm)
```suggestion
```

2022-12-26 10:03 UTC, kduret commented on .github/actions/rpm-delivery/action.yml
> +          ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "ls -drc $PROJECT_LOCATION/* 2>&- | head -n -6 | xargs rm -rf"
as discussed, we should keep only last directory
```suggestion
          ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "ls -drc $PROJECT_LOCATION/* 2>&- | head -n -1 | xargs rm -rf"
```

2022-12-29 13:47 UTC, bdauria approved these changes

2023-01-02 13:28 UTC, kduret approved these changes

2023-01-02 13:54 UTC, totogtr requested changes

2023-01-02 13:54 UTC, totogtr commented on .github/workflows/widget-delivery.yml
>          uses: ./.github/actions/rpm-delivery
I suppose `minor_version` should be also passed to `rpm-delivery` action

2023-01-02 14:05 UTC, totogtr approved these changes

2023-01-02 14:35 UTC, merged