enh(SQL): Enh sql in export of widget host monitoring
centreon/centreon pull request #6076
Opened 2024-12-11 18:30 UTC by asalhi-ext

Enh sql in export of widget host monitoring

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [x] master

<h2> How this pull request can be tested ? </h2>

Check [Ticket](https://centreon.atlassian.net/browse/MON-151845)

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2024-12-16 16:06 UTC, adr-mo approved these changes

2024-12-16 16:13 UTC, callapa requested changes

2024-12-16 23:20 UTC, asalhi-ext commented on centreon/www/widgets/host-monitoring/src/export.php
> +    $baseQuery .= 'AND h.host_id IN (' . $hostQuery . ') ';
done

2024-12-17 08:31 UTC, callapa approved these changes

2024-12-17 08:50 UTC, adr-mo approved these changes

2024-12-17 23:17 UTC, merged