enh(conf) call patch endpoints for host/hostTemplate update by form
centreon/centreon pull request #6185
Opened 2024-12-18 10:59 UTC by a-launois

## Description

Call PATCH endpoints in legacy forms to update host & host Template.

I suggest reviewing by commit :
- 1st commit : reorganisation of the DB-Func methods (no changes, just moving functions).
- 2nd commit : where the real changes take place.
- 3rd commit : a general code style on the DB-Func.

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [x] master

2025-01-02 09:33 UTC, callapa commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
Why don't you pass variables directly using function parameters?

2025-01-07 10:01 UTC, jeremyjaouen commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +                            AND hc.level IS NOT NULL) ';
Identation

2025-01-07 16:33 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
Multiple reasons:
- formData are fetched the smae way in other function in this file and in other DB-Func files.
- I can keep the function signature the same as before
- I find the code clearer like that

2025-01-08 08:28 UTC, jeremyjaouen approved these changes

2025-01-10 13:48 UTC, callapa commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
> formData are fetched the smae way in other function in this file and in other DB-Func files.

Let's not keep bad habits.

> I can keep the function signature the same as before

I don't see the difficulty in changing two function calls. Especially since the method arguments have been modified and the effort has been made for the insertByApi function.

> I find the code clearer like that

Good practices remain a priority.

2025-01-13 08:11 UTC, Drago37 requested changes
Code with a legacy is never easy. But we can improve the DX step by step : new methods, logs, phpdocs, typing, tests etc...). we don't have to put up with legacy, we have to bring it to life :) 
Also, you could create a class with your services to isolate it from legacy, for example.

2025-01-13 08:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>      }
not a good practice to sen the message of exception at the user. Also you must to log this catch with CentreonLog please.

2025-01-13 08:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return false;
not a good practice to sen the message of exception at the user. Also you must to log this catch with CentreonLog please.

2025-01-13 08:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
Yes I am agree with @callapa :)

2025-01-13 08:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>          $content = json_decode($response->getContent(false));
json_encode can return false, you can pass in arguments the flag [JSON_THROW_ON_ERROR](https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error). Thanks.

2025-01-13 08:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>              'body' => json_encode($payload),
json_encode can return false, you can pass in arguments the flag [JSON_THROW_ON_ERROR](https://www.php.net/manual/en/json.constants.php#constant.json-throw-on-error). Thanks.

2025-01-13 08:14 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>          $content = json_decode($response->getContent(false));
And you can catch the JsonException to log the error to adapt the response ;)

2025-01-13 08:14 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>              'body' => json_encode($payload),
And you can catch the JsonException to log the error to adapt the response ;)

2025-01-13 08:29 UTC, selfakiri commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $centreon->CentreonLogAction->insertLog(
Hello, this might duplicate ActionLog insertion that exists in the API.

2025-01-15 15:51 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $hostName = CentreonDB::escape($centreon->checkIllegalChar($name));
This was not modified

2025-01-15 15:51 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $prepare->bindValue(':host_name', $hostName, PDO::PARAM_STR);
This was not modified

2025-01-15 15:51 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function testCg($list)
It is used in the form, it a validation rule

2025-01-15 15:52 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function hostMacHandler()
This was not modified

2025-01-15 15:52 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $result = $prepare->fetch(PDO::FETCH_ASSOC);
This was not modified

2025-01-15 16:26 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $dbResult = $pearDB->query($rq);
This was not modified

2025-01-15 16:27 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function serviceIsInUse($svc_id, $host_list)
This was not modified

2025-01-15 16:27 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function getHostListInUse($hst_list, $hst)
This was not modified

2025-01-15 16:27 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function applytpl($hosts): void
This was not modified

2025-01-15 16:27 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifs($host_id = null, $ret = []): void
This was not modified

2025-01-15 16:28 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifs($host_id = null, $ret = []): void
it's the formData, most of the timein legacy  it is not provided and is empty

2025-01-15 16:28 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    }
This was not modified

2025-01-15 16:28 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifOptionInterval($host_id = null, $ret = []): void
This was not modified

2025-01-15 16:28 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifOptionInterval($host_id = null, $ret = []): void
This was not modified

2025-01-15 16:31 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>      }
I added logs, but as explained we have to keep this for the moment

2025-01-15 16:31 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
Modified

2025-01-15 16:32 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $centreon->CentreonLogAction->insertLog(
I removed the double call to ActionLog

2025-01-15 16:32 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return false;
Same as above

2025-01-15 16:33 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>              'body' => json_encode($payload),
Done

2025-01-15 16:33 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>          $content = json_decode($response->getContent(false));
Done

2025-01-17 14:08 UTC, selfakiri approved these changes

2025-01-21 06:32 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $formData = $form->getSubmitValues();
It's ok for me but I keep @callapa to check and resolve.

2025-01-21 06:33 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $hostName = CentreonDB::escape($centreon->checkIllegalChar($name));
Ok seen together, I rselve.

2025-01-21 06:37 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $prepare->bindValue(':host_name', $hostName, PDO::PARAM_STR);
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:38 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function testCg($list)
ok thanks

2025-01-21 06:38 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function hostMacHandler()
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:38 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        $result = $prepare->fetch(PDO::FETCH_ASSOC);
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:38 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        . "AND hsr.host_host_id = '" . $scndHID . "'");
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:38 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    $dbResult = $pearDB->query($rq);
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function serviceIsInUse($svc_id, $host_list)
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function getHostListInUse($hst_list, $hst)
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function applytpl($hosts): void
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifs($host_id = null, $ret = []): void
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:40 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    }
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:40 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifOptionInterval($host_id = null, $ret = []): void
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:40 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifOptionInterval($host_id = null, $ret = []): void
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:42 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function updateHostNotifs($host_id = null, $ret = []): void
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 06:42 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    }
Ok seen together, I resolve because you didn't modify this code.

2025-01-21 07:00 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>      }
ok for me, can you replace the error_log() by CentreonLog too please ? Two times in the code, you can serach Throwable to find it. It will be perfect :) Thanks a lot.

2025-01-21 07:04 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return false;
Ok. You can remove the ':' at the exception key in the context and you can complete by :
`'exception' => ['message' => $ex->getMessage(), 'trace' => $ex->getTraceAsString()],`.
In the JsonException catch an Throwable catch

2025-01-21 07:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return null;
In the JsonException catch you return false, I think it's a better idea than return null, also, you return false in the update function. Can you replace the null return by a false please ? thanks.
Return null it's not a good practice for the type of function :)

2025-01-21 07:11 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>          $content = json_decode($response->getContent(false));
top !

2025-01-21 07:12 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>              'body' => json_encode($payload),
ok

2025-01-21 07:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    return;
return alone it's not a good practice, you can return the response of callapi() ;) and change the signature of this method void => int|null
Sorry I can't suggest because of deleted lines :(

2025-01-21 07:39 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function insertByApi(array $formData, bool $isCloudPlatform, string $basePath, bool $isTemplate): int
Beware, callapi return int or null. here you return only int. If you want return int, you can place a cast int before return callApi().

2025-01-24 09:01 UTC, jeremyjaouen approved these changes

2025-01-27 06:54 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
>      }
good

2025-01-27 06:54 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return false;
good

2025-01-27 06:55 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        return null;
good !

2025-01-27 06:55 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    return;
ok

2025-01-27 06:56 UTC, Drago37 commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function insertByApi(array $formData, bool $isCloudPlatform, string $basePath, bool $isTemplate): int
ok

2025-01-27 06:56 UTC, Drago37 approved these changes

2025-01-27 08:22 UTC, callapa commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _('Error during update (json encoding). See logs for more detail') . '</div>';
Technical errors do not have to be displayed to the user.

2025-01-27 08:32 UTC, callapa commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +            ? (int) $formData['ehi_icon_image']
Casting a string as an integer can lead to unexpected behavior
`(int) "hello"` => 0 (In our database system, all identifiers are > 0)

2025-01-28 11:01 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +        echo "<div class='msg' align='center'>" . _('Error during update (json encoding). See logs for more detail') . '</div>';
```suggestion
        echo "<div class='msg' align='center'>" . _('Error during update. See logs for more detail or contact your administrator.') . '</div>';
```

2025-01-28 11:03 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +            ? (int) $formData['ehi_icon_image']
It's for the API payload, the validation of the payload will handled this kind of error

2025-01-28 11:12 UTC, Drago37 approved these changes

2025-01-28 13:58 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +function callApi(string $url, string $httpMethod, array $payload): int|null
```suggestion
function callHostApi(string $url, string $httpMethod, array $payload): int|null
```

2025-01-28 13:58 UTC, a-launois commented on centreon/www/include/configuration/configObject/host/DB-Func.php
> +    return callApi($url, 'POST', $payload);
```suggestion
    return callHostApi($url, 'POST', $payload);
```

2025-01-29 08:40 UTC, dmyios approved these changes

2025-01-30 09:00 UTC, merged