enh(RS): add flapping and percent state change to find resources
centreon/centreon pull request #6200
Opened 2024-12-19 14:06 UTC by jeremyjaouen

## Description

This PR intends to Add Flapping and percent state change to Find Resources endpoint.

```json
{
    "result": [
        {
            "uuid": "h14-s25",
            "duration": "17m 13s",
            . . .
            "is_in_flapping": false,
            "percent_state_change": null
            . . .
        },
    ],
    "meta": {
        "page": 1,
        "limit": 30,
        "search": {
            "$and": []
        },
        "sort_by": {
            "last_status_change": "DESC"
        },
        "total": 3
    }
}
```

This also add a new filter for states: "in_flapping"

**Fixes** # MON-153871

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [x] 24.04.x
- [x] 24.10.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2024-12-19 14:16 UTC, Drago37 requested changes

2024-12-19 14:16 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +    public function isFlapping(): bool
php doc to update :)

2024-12-19 14:16 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +    public function setIsFlapping(bool $flapping): self
php doc to update

2024-12-19 14:16 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->executeQuery(
executeQuery is not used for a DDL context, you can use exec() from PDO, a new method will be created for the DDL.

2024-12-19 14:16 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->executeQuery(
executeQuery is not used for a DDL context, you can use exec() from PDO, a new method will be created for the DDL.

2024-12-19 14:16 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->rollBack();
try catch PDO exception and log the error with CentreonLog please ;)

2024-12-19 14:16 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +    );
use new CentreonLog Methods like error() please and pass the exception in option.

2024-12-30 17:42 UTC, callapa commented on centreon/src/Core/Resources/Infrastructure/API/FindResources/FindResourcesPresenter.php
> +                    'is_in_flapping' => $resource->isFlapping,
```suggestion
                    'is_in_flapping' => $resource->isInFlapping,
```

2025-01-08 07:53 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +    public function isFlapping(): bool
it's ok I resolve :) Thanks for your change.

2025-01-08 07:55 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +        return $this->isFlapping;
isflapping or isInFlapping ?

2025-01-08 07:55 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +    public function setIsFlapping(bool $flapping): self
it's ok I resolve :) Thanks for your change.

2025-01-08 07:55 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->executeQuery(
it's ok I resolve :) Thanks for your change.

2025-01-08 07:56 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->executeQuery(
it's ok I resolve :) Thanks for your change.

2025-01-08 07:56 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->rollBack();
not done

2025-01-08 07:57 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +    );
not done completely, the message must be simple, use the context to pass the information ;)

2025-01-08 10:33 UTC, Drago37 requested changes

2025-01-08 10:33 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +}
Note that the rollback exception is missing. I've made a few adjustments (context, variable dedicated to rollback, PDO errors), so I suggest you this :

```suggestion
} catch (\PDOException $e) {
    try {
        if ($pearDBO->inTransaction()) {
            $pearDBO->rollBack();
        }
    } catch (\PDOException $rollbackException) {
        $rollbackErrorMessage = $versionOfTheUpgrade . "error while rolling back transaction : {$rollbackException->getMessage()}";
        $centreonLog->error(
            logTypeId: CentreonLog::TYPE_UPGRADE,
            message: $rollbackErrorMessage,
            customContext: [
                'exception_message' => $rollbackException->getMessage(),
                'pdo_error_code' => $rollbackException->getCode(),
                'pdo_error_info' => $rollbackException->errorInfo,
                'trace' => $rollbackException->getTraceAsString(),
            ],
            exception: $rollbackException
        );

        throw new Exception($rollbackErrorMessage, (int) $rollbackException->getCode(), $rollbackException);
    }

    $centreonLog->error(
        logTypeId: CentreonLog::TYPE_UPGRADE,
        message: $versionOfTheUpgrade . $errorMessage
        . ' - Code : ' . (int) $e->getCode()
        . ' - Error : ' . $e->getMessage()
        . ' - Trace : ' . $e->getTraceAsString(),
        customContext: [
            'exception_message' => $e->getMessage(),
            'pdo_error_code' => $e->getCode(),
            'pdo_error_info' => $e->errorInfo,
            'trace' => $e->getTraceAsString(),
        ],
        exception: $e
    );

    throw new Exception($versionOfTheUpgrade . $errorMessage, (int) $e->getCode(), $e);
}
```

2025-01-08 10:34 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +        $pearDB->rollBack();
ok but a RC in progress because missing an exception :) see https://github.com/centreon/centreon/pull/6200#discussion_r1906970520

2025-01-08 10:35 UTC, Drago37 commented on centreon/www/install/php/Update-25.01.0.php
> +    );
ok

2025-01-08 10:36 UTC, Drago37 commented on centreon/src/Centreon/Domain/Monitoring/Resource.php
> +        return $this->isFlapping;
Thanks !

2025-01-08 11:17 UTC, Drago37 approved these changes

2025-01-08 13:55 UTC, callapa approved these changes

2025-01-09 08:54 UTC, merged