fea (user): new API endpoint to list user permissions
centreon/centreon pull request #6218
Opened 2024-12-20 15:11 UTC by callapa

## Description

Create a new API endpoint to list user permissions
```
GET /api/latest/users/acl/permissions

{
    'top-counter': bool,
}
```

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 22.10.x
- [ ] 23.04.x
- [ ] 23.10.x
- [ ] 24.04.x
- [ ] 24.10.x
- [x] master

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2025-01-08 07:33 UTC, Drago37 reviewed
Questions and suggestions :)

2025-01-08 07:33 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
> +        $this->denyAccessUnlessGrantedForApiConfiguration();
I thought it wasn't necessary.  Also, no voter here ?

2025-01-08 07:33 UTC, Drago37 commented on centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
> +    public function __construct(private readonly ObjectNormalizer $normalizer)
If the class is readonly, you don't need to use readonly for the propertie ;)

2025-01-08 07:33 UTC, Drago37 commented on centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
mixed no ? :)

2025-01-08 07:33 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsResponseNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
mixed ? :)

2025-01-08 07:33 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/PermissionNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
mixed ? :)

2025-01-08 09:14 UTC, jeremyjaouen requested changes

2025-01-08 09:14 UTC, jeremyjaouen commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
> +        $this->denyAccessUnlessGrantedForApiConfiguration();
```suggestion
```
As @Drago37  says it is not needed, but I think no voters here are needed, as we don't check any rights, just return the permissions of the users executing the request

2025-01-08 09:47 UTC, callapa commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
> +        $this->denyAccessUnlessGrantedForApiConfiguration();
No voter here

2025-01-13 08:21 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
> +        $this->denyAccessUnlessGrantedForApiConfiguration();
ok

2025-01-13 08:22 UTC, Drago37 commented on centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
ok

2025-01-13 08:23 UTC, Drago37 commented on centreon/src/Core/Common/Infrastructure/Normalizer/NotEmptyStringNormalizer.php
> +    public function __construct(private readonly ObjectNormalizer $normalizer)
ok

2025-01-13 08:23 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsResponseNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
ok

2025-01-13 08:23 UTC, jeremyjaouen approved these changes

2025-01-13 08:24 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/PermissionNormalizer.php
> +    ): float|int|\ArrayObject|bool|array|string|null
ok

2025-01-13 08:25 UTC, Drago37 commented on centreon/src/Core/User/Infrastructure/API/FindUserPermissions/FindUserPermissionsController.php
> +        $this->denyAccessUnlessGrantedForApiConfiguration();
I resolve this RC ;) @jeremyjaouen

2025-01-13 08:26 UTC, Drago37 approved these changes
thanks for your changes ;)

2025-01-13 10:04 UTC, merged