feat(APIv2): add a DELETE endpoint for host severities
centreon/centreon pull request #666
Opened 2023-01-10 16:39 UTC by abuathier

## Description

Jira: MON-15458

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [X] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Look at the Jira ticket.

## Checklist

#### Community contributors & Centreon team

- [X] I have followed the **coding style guidelines** provided by Centreon
- [X] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [X] I have commented my code, especially **hard-to-understand areas** of the PR.
- [X] I have **rebased** my development branch on the base branch (master, maintenance).

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Vous n'êtes pas autorisé à créer des sévérités d'hôtes"
```suggestion
msgstr "Vous n'êtes pas autorisé à supprimer des criticités d'hôtes"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur durant la suppression d'une sévérité d'hôtes"
```suggestion
msgstr "Erreur durant la suppression d'une criticité d'hôtes"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Erreur lors de la création d'une sévérité d'hôtes"
```suggestion
msgstr "Erreur lors de la création d'une criticité d'hôtes"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Vous n'êtes pas autorisé à créer des sévérités d'hôtes"
```suggestion
msgstr "Vous n'êtes pas autorisé à créer des criticités d'hôtes"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Error lors de la récupération de la sévérité d'hôtes nouvellement créée"
```suggestion
msgstr "Error lors de la récupération de la criticité d'hôtes nouvellement créée"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "Ce nom de sévérité d'hôtes existe déjà"
```suggestion
msgstr "Ce nom de criticité d'hôtes existe déjà"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
> +msgstr "L'icône de sévérité d'hôtes avec l'identifiant '%d' n'existe pas"
```suggestion
msgstr "L'icône de criticité d'hôtes avec l'identifiant '%d' n'existe pas"
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                    'Host severity icon does not exists',
```suggestion
                    'Host severity icon does not exist',
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/tests/php/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityTest.php
> +it('should present an ConflictResponse when name is already used', function (): void {
```suggestion
it('should present a ConflictResponse when name is already used', function (): void {
```

2023-01-18 09:45 UTC, cg-tw commented on centreon/tests/php/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverityTest.php
> +it('should throw an ConflictResponse if the host severity icon does not exist', function (): void {
```suggestion
it('should throw a ConflictResponse if the host severity icon does not exist', function (): void {
```

2023-01-18 13:03 UTC, cg-tw approved these changes

2023-01-20 08:15 UTC, jeremyjaouen approved these changes

2023-01-20 10:11 UTC, adr-mo approved these changes

2023-01-20 15:05 UTC, callapa requested changes

2023-01-20 15:05 UTC, callapa commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                $newHostSeverity->setComment($request->comment ? trim($request->comment) : null);
```suggestion
                $newHostSeverity->setComment($request->comment ?$request->comment : null);
```
Same remark as above

2023-01-20 15:05 UTC, callapa commented on centreon/src/Core/HostSeverity/Application/UseCase/DeleteHostSeverity/DeleteHostSeverity.php
> +                    $presenter->setResponseStatus(new NoContentResponse());
Log missing

2023-01-20 15:08 UTC, callapa commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                $hostSeverity = $this->readHostSeverityRepository->findById($hostSeverityId);
missing log

2023-01-20 16:10 UTC, abuathier commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                $newHostSeverity->setComment($request->comment ? trim($request->comment) : null);
✅ done with added tests

2023-01-20 16:10 UTC, abuathier commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                    trim($request->alias),
✅ done with added tests

2023-01-20 16:13 UTC, abuathier commented on centreon/src/Core/HostSeverity/Application/UseCase/DeleteHostSeverity/DeleteHostSeverity.php
> +                    $presenter->setResponseStatus(new NoContentResponse());
✅ done

2023-01-20 16:13 UTC, abuathier commented on centreon/src/Core/HostSeverity/Application/UseCase/AddHostSeverity/AddHostSeverity.php
> +                $hostSeverity = $this->readHostSeverityRepository->findById($hostSeverityId);
✅ done

2023-01-23 11:15 UTC, callapa approved these changes

2023-01-23 11:17 UTC, merged