fix[style]: Refacto display of forms centreon web
centreon/centreon pull request #741
Opened 2023-01-23 15:49 UTC by emabassi-ext

## Description

Refacto the display of all configuration/paremeter form.

**Fixes** # MON-16111

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Labels must take maximum 33 characters spaces included . 
 
check on the pages with the longest labels the impact on the height of the lines

 space  32 pixel between labels and fields. 

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-01-23 18:23 UTC, Thebarda commented on centreon/www/Themes/Generic-theme/style.css
> +    width: 206px;
Use responsive units such as "%" or "vw"

2023-01-24 12:44 UTC, Wedierre requested changes
Be careful to align the beginning of sentences, for all sentences that are on several lines.
see on the screenshot for exemple
<img width="1502" alt="Capture d’écran 2023-01-24 à 13 39 08" src="https://user-images.githubusercontent.com/106759752/214294828-d5a5228b-66ee-44db-8cd9-10fb63fdc069.png">

2023-01-27 13:12 UTC, Wedierre commented
> but when there is a tooltips before texte the new line starts with the circled question mark

Align text with the beginning of the sentence, not the pictogram
<img width="726" alt="Capture d’écran 2023-01-27 à 14 06 57" src="https://user-images.githubusercontent.com/106759752/215095079-e7923096-0b8c-43f5-8d92-87f52ac0a3a6.png">

2023-02-07 09:11 UTC, Wedierre reviewed
on all screen copies there is a problem of centering the text and pictorial on the height of the lines.
<img width="1501" alt="Capture d’écran 2023-02-07 à 09 54 07" src="https://user-images.githubusercontent.com/106759752/217201284-5b472c63-c76b-4712-9dd6-9cc86d22dfbd.png">
<img width="1501" alt="Capture d’écran 2023-02-07 à 10 02 14" src="https://user-images.githubusercontent.com/106759752/217201291-30c5ae8e-e497-42d4-88e5-747e1272eb6d.png">
<img width="1494" alt="Capture d’écran 2023-02-07 à 10 01 46" src="https://user-images.githubusercontent.com/106759752/217201299-7b27395d-9b0d-4078-806c-d35d74d2e608.png">
<img width="1503" alt="Capture d’écran 2023-02-07 à 10 00 33" src="https://user-images.githubusercontent.com/106759752/217201302-02a3c774-ba71-4e31-a660-b8d873785f8f.png">
<img width="1501" alt="Capture d’écran 2023-02-07 à 09 59 47" src="https://user-images.githubusercontent.com/106759752/217201303-425661c2-3d31-4f42-8a58-bc58933133b5.png">
<img width="1496" alt="Capture d’écran 2023-02-07 à 09 59 11" src="https://user-images.githubusercontent.com/106759752/217201307-56eb17c0-f7cf-4d1c-8d2f-734fc1f5d2b5.png">
<img width="1503" alt="Capture d’écran 2023-02-07 à 09 58 12" src="https://user-images.githubusercontent.com/106759752/217201311-92104afd-b88b-4eef-ada3-f9e864f426eb.png">
<img width="1502" alt="Capture d’écran 2023-02-07 à 09 57 34" src="https://user-images.githubusercontent.com/106759752/217201316-26123781-d44a-4aa4-8b7f-6c6e52905ef5.png">
<img width="1499" alt="Capture d’écran 2023-02-07 à 09 55 44" src="https://user-images.githubusercontent.com/106759752/217201320-821f4742-9888-42c9-badc-bcfca10830cd.png">
<img width="1493" alt="Capture d’écran 2023-02-07 à 09 52 44" src="https://user-images.githubusercontent.com/106759752/217201326-ae48dd68-d36f-4b98-aef0-2773ec9d03d7.png">
<img width="1493" alt="Capture d’écran 2023-02-07 à 09 29 04" src="https://user-images.githubusercontent.com/106759752/217201331-09af403d-b43d-445d-835e-6e31fc0e6c81.png">
<img width="1501" alt="Capture d’écran 2023-02-07 à 09 21 38" src="https://user-images.githubusercontent.com/106759752/217201334-0285cc84-659e-46e8-994b-aa595bf12da8.png">

Can you fix it easily?

2023-02-16 14:35 UTC, bdauria approved these changes

2023-02-16 16:45 UTC, Wedierre approved these changes

2023-02-17 11:04 UTC, kduret approved these changes

2023-02-17 11:10 UTC, jeremyjaouen approved these changes

2023-02-17 11:13 UTC, merged