Next 22.04 release #18981
centreon/centreon pull request #825
Opened 2023-01-31 17:06 UTC by tuntoja

Centreon 22.04 next release #18981#

2023-01-31 17:11 UTC, wtermellil requested changes

2023-01-31 17:11 UTC, wtermellil commented on centreon/www/install/php/Update-22.04.10.php
> + * Copyright 2005 - 2022 Centreon (https://www.centreon.com/)
2005 - 2023

2023-01-31 17:12 UTC, tuntoja commented on centreon/www/install/php/Update-22.04.10.php
> + * Copyright 2005 - 2022 Centreon (https://www.centreon.com/)
indeed, updating in progress

2023-01-31 17:13 UTC, tuntoja commented on centreon/www/install/php/Update-22.04.10.php
> + * Copyright 2005 - 2022 Centreon (https://www.centreon.com/)
done @wtermellil

2023-01-31 17:15 UTC, wtermellil submitted a review, later dismissed

2023-02-01 08:32 UTC, abuathier submitted a review, later dismissed

2023-02-01 09:53 UTC, abuathier approved these changes

2023-02-07 11:32 UTC, merged