fix(security) sanitize contact groups
centreon/centreon pull request #9220
Opened 2020-11-19 14:50 UTC by loiclau

## Description

sanitize ContactGroups form

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2020-11-19 14:56 UTC, kduret reviewed
Please update your PR description
If you don't fill some parts of the PR template, remove those

2020-11-19 15:04 UTC, sc979 requested changes

2020-11-19 15:04 UTC, sc979 commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $stmt->bindValue(':cgComment', $cgComment, \PDO::PARAM_STR);
what will happen if comment contains only illegal chars ?
filter_var will return false and bindValue will try to bind false
same for other fields

2020-11-19 15:04 UTC, sc979 commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgComment = filter_var($ret["cg_comment"], FILTER_SANITIZE_STRING);
same comment

2020-11-19 15:04 UTC, sc979 commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $stmt->bindValue(':cgComment', $cgComment, \PDO::PARAM_STR);
IMHO : you'll need to check that each of the sanitized variable are different from false

2020-11-19 15:53 UTC, loiclau commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgComment = filter_var($ret["cg_comment"], FILTER_SANITIZE_STRING) ?: '';
```suggestion
    $cgComment = filter_var($ret["cg_comment"], FILTER_SANITIZE_STRING);
```

2020-11-19 16:19 UTC, loiclau commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING) ?: '1'; //enum
```suggestion
    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING); //enum
    $cgActivate = ($cgActivate === '0' ? '0' : '1');
```

2020-11-19 16:20 UTC, loiclau commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING) ?: '1'; //enum
```suggestion
    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING); //enum
    $cgActivate = ($cgActivate === '0' ? '0' : '1');
```

2020-11-19 17:05 UTC, sc979 commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING); //enum
this line seems obsolete, as the enum will returns the state of the checkbox, which is checked on next line

2020-11-20 08:29 UTC, jeremyjaouen commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = filter_var($ret["cg_activate"]["cg_activate"], FILTER_SANITIZE_STRING); //enum
https://github.com/centreon/centreon/pull/9220/files#r527052510

2020-11-23 08:16 UTC, jeremyjaouen submitted a review, later dismissed

2020-11-24 08:04 UTC, sc979 submitted a review, later dismissed

2020-11-26 09:59 UTC, loiclau commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = ($ret["cg_activate"]["cg_activate"] === '0' ? '0' : '1');//enum
```suggestion
    $cgActivate = $ret["cg_activate"]["cg_activate"] === '0' ? '0' : '1';//enum
```

2020-11-26 09:59 UTC, loiclau commented on www/include/configuration/configObject/contactgroup/DB-Func.php
> +    $cgActivate = ($ret["cg_activate"]["cg_activate"] === '0' ? '0' : '1');//enum
```suggestion
    $cgActivate = $ret["cg_activate"]["cg_activate"] === '0' ? '0' : '1';//enum
```

2020-11-26 13:16 UTC, jeremyjaouen approved these changes

2020-11-26 13:27 UTC, sc979 approved these changes

2020-11-26 13:53 UTC, merged