Mon 12216
centreon/centreon pull request #924
Opened 2023-02-14 14:26 UTC by s-duret

## Description

The "updated" column of nagios_server was updated when we reload/restart threw the GUI but not from CLAPI.

**Fixes** MON-12216

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

2023-02-15 14:07 UTC, abuathier submitted a review, later dismissed

2023-02-16 06:39 UTC, wtermellil approved these changes

2023-02-16 10:52 UTC, a-launois requested changes
Not sure it's the best place to add this modification, I'll have a look at it and come back to you

2023-02-16 11:08 UTC, a-launois approved these changes
Well, apparently it's the same behaviour in the UI so OK

2023-02-27 13:25 UTC, a-launois approved these changes

2023-02-27 13:25 UTC, abuathier approved these changes

2023-02-27 13:28 UTC, merged