enh(unattended): unattended immediatly check if run by root
centreon/centreon pull request #9746
Opened 2021-04-27 09:44 UTC by Nohzoh

The `unattended.sh` script must be run by root.
This change adds an immediate and explicit control of this requirement.

2021-04-27 10:00 UTC, lgcosta approved these changes

2021-04-27 10:32 UTC, sc979 commented on unattended.sh
> +if [[ $EUID -ne 0 ]]; then
why not use whoami ?

2021-04-27 10:36 UTC, sc979 commented on unattended.sh
> +if [[ $EUID -ne 0 ]]; then
got my answer : may be runned using sudo

2021-04-27 10:36 UTC, sc979 submitted a review, later dismissed

2021-04-27 10:40 UTC, lgcosta requested changes

2021-04-27 10:40 UTC, lgcosta commented on unattended.sh
> +if [[ $EUID -ne 0 ]]; then
```suggestion
if [ $EUID -ne 0 ]; then
```
Use one brackets for POSIX format compatible (example pure sh)

2021-04-27 12:47 UTC, lgcosta approved these changes

2021-04-28 07:53 UTC, adr-mo approved these changes

2021-04-28 11:28 UTC, merged