[enh]: configure mariadb with utf8mb4 by default
centreon/centreon pull request #991
Opened 2023-02-22 11:07 UTC by emabassi-ext

## Description

In order to manage emoji, Mariadb and Mysql have a 4 bytes encoded UTF8 charset called utf8mb4.

Modern monitoring tools should  allows to use emoji to spread messages to anyone and anywhere.

 set the database charset by default at utf8mb4 at install.

- Only change database charset for new installation

- Develop a script to perform update manually (in centreon/tools/)

 
**Fixes** # MON-7025

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [x] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

1. Install a new Centreon 23.04 platform
2. Add emoji in host / service / Meta / BA name
3. Export configuration
4. Check that resources name are correctly displayed in Resource Status pages
5. Install a Centreon platform < 23.04
6. Run manually database script update (DEV to put script name)
7. Add emoji in host / service / Meta / BA name
8. Export configuration
9. Check that resources name are correctly displayed in Resource Status pages

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2023-02-22 13:31 UTC, a-launois requested changes

2023-02-22 13:31 UTC, a-launois commented on centreon/www/install/createTables.sql
> +/*!40101 SET SET character_set_client = utf8mb4 */;
You have a double SET in the whole file:
```suggestion
/*!40101 SET character_set_client = utf8mb4 */;
```

2023-02-24 09:39 UTC, jeremyjaouen commented on centreon/tools/convert_db_charset_to_utfmb4.php
> +        echo "All tables of " . $dbName . " have had their charset converted.\n";
```suggestion
        echo "All tables of " . $dbName . " had their charset converted.\n";
```

2023-02-24 10:42 UTC, jeremyjaouen submitted a review, later dismissed

2023-02-27 08:46 UTC, abuathier commented on centreon/tools/convert_db_charset_to_utfmb4.php
> +            // Check if the table is a view, and skip it if it is
Simpler
```suggestion
            // Skip the table if it is a view
```

2023-02-28 08:16 UTC, jeremyjaouen approved these changes

2023-02-28 08:17 UTC, a-launois approved these changes

2023-02-28 08:25 UTC, merged