fix(downtimes): SQL request fixed on downtime action
centreon/centreon pull request #993
Opened 2023-02-22 14:46 UTC by adr-mo

## Description

This PR intends to fix an issue with the SQL request

🏷️ MON-16768

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.10.x
- [x] 22.04.x
- [x] 22.10.x
- [x] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

See MON-16768

## Checklist

#### Community contributors & Centreon team

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-02-22 15:23 UTC, abuathier approved these changes

2023-02-22 15:55 UTC, a-launois requested changes

2023-02-22 15:55 UTC, a-launois commented on centreon/www/include/monitoring/external_cmd/cmdPopup.php
> +const AKNOWLEDGEMENT_ON_HOST = 72;
```suggestion
const ACKNOWLEDGEMENT_ON_SERVICE = 70;
const ACKNOWLEDGEMENT_ON_HOST = 72;
```

2023-02-22 15:55 UTC, a-launois commented on centreon/www/include/monitoring/external_cmd/cmdPopup.php
> +            case AKNOWLEDGEMENT_ON_HOST:
```suggestion
            case ACKNOWLEDGEMENT_ON_SERVICE:
                massiveServiceAck($resource);
                break;
            case ACKNOWLEDGEMENT_ON_HOST:
```

2023-02-22 17:17 UTC, a-launois approved these changes

2023-02-23 08:11 UTC, abuathier approved these changes

2023-02-23 13:36 UTC, a-launois approved these changes

2023-02-23 13:37 UTC, jeremyjaouen submitted a review, later dismissed

2023-02-23 13:59 UTC, abuathier approved these changes

2023-02-23 14:00 UTC, jeremyjaouen approved these changes

2023-02-23 14:35 UTC, merged